import os
from dotenv import load_dotenv
load_dotenv()

EMAIL_CONFIG = {
    "sender_email":    os.getenv("GMAIL_SENDER", "your_gmail@gmail.com"),
    "sender_password": os.getenv("GMAIL_APP_PASSWORD", "your_app_password"),
    "recipient_email": os.getenv("GMAIL_RECIPIENT", "your_gmail@gmail.com"),
    "smtp_host":       "smtp.gmail.com",
    "smtp_port":       465,
}

SEARCH_KEYWORDS = [
    "Senior Data Engineer", "Data Engineer", "Analytics Engineer",
    "Data Platform Engineer", "ML Data Engineer", "Cloud Data Engineer",
]

EXPERIENCE_LEVELS = ["Senior", "Mid-Level", "Entry Level", "Staff", "Principal"]

TARGET_LOCATIONS = [
    "Canada", "Toronto", "Vancouver", "Calgary", "Edmonton",
    "Halifax", "Ottawa", "Montreal", "Remote", "Hybrid",
]

MAX_JOBS_PER_EMAIL = 50
SEEN_JOBS_FILE = "data/seen_jobs.json"

COMPANIES = [
    # ══ BANKS & INSURANCE ══
    {"name":"RBC","careers_url":"https://jobs.rbc.com/ca/en/search-results?keywords=data+engineer","category":"Banks","scraper":"phenom","top100":True,"titles":["Senior Data Engineer","Analytics Engineer","Data Platform Engineer"],"stack":["Azure","Databricks","Spark","Python","dbt"],"locations":["Toronto","Vancouver","Calgary"],"salary_range":"$85K-$215K"},
    {"name":"TD Bank","careers_url":"https://td.wd3.myworkdayjobs.com/TD_Bank_Careers?q=data+engineer&locationCountry=a30a87ed25634629aa6c3958aa2b91ea","category":"Banks","scraper":"workday","top100":True,"titles":["Senior Data Engineer","ETL Developer","Analytics Engineer"],"stack":["Azure","Snowflake","Python","dbt","Airflow"],"locations":["Toronto","Montreal"],"salary_range":"$80K-$210K"},
    {"name":"Scotiabank","careers_url":"https://jobs.scotiabank.com/search-results?keywords=data+engineer&location=Canada","category":"Banks","scraper":"custom","top100":True,"titles":["Senior Data Engineer","Data Platform Engineer","Analytics Engineer"],"stack":["Azure","Databricks","PySpark","Python","dbt"],"locations":["Toronto","Montreal"],"salary_range":"$80K-$212K"},
    {"name":"CIBC","careers_url":"https://cibc.wd3.myworkdayjobs.com/search?q=data+engineer","category":"Banks","scraper":"workday","top100":True,"titles":["Senior Data Engineer","ETL Developer","Analytics Engineer"],"stack":["Azure","Spark","Python","SQL","ADF"],"locations":["Toronto"],"salary_range":"$78K-$208K"},
    {"name":"BMO Financial Group","careers_url":"https://jobs.bmo.com/ca/en/search-results?keywords=data+engineer","category":"Banks","scraper":"phenom","top100":True,"titles":["Senior Data Engineer","Data Platform Engineer","Analytics Engineer"],"stack":["Azure","Databricks","Python","dbt","Spark"],"locations":["Toronto","Montreal"],"salary_range":"$82K-$215K"},
    {"name":"National Bank of Canada","careers_url":"https://nbc.wd3.myworkdayjobs.com/search?q=data+engineer","category":"Banks","scraper":"workday","top100":True,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["Azure","Python","Spark","SQL","dbt"],"locations":["Montreal","Toronto"],"salary_range":"$78K-$210K"},
    {"name":"Manulife","careers_url":"https://careers.manulife.com/global/en/search-results?keywords=data+engineer","category":"Banks","scraper":"phenom","top100":True,"titles":["Senior Data Engineer","Data Platform Engineer","Analytics Engineer"],"stack":["AWS","Snowflake","Python","dbt","Airflow"],"locations":["Toronto","Waterloo"],"salary_range":"$82K-$215K"},
    {"name":"Sun Life Financial","careers_url":"https://sunlife.wd3.myworkdayjobs.com/search?q=data+engineer","category":"Banks","scraper":"workday","top100":True,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["AWS","Azure","Python","Spark","SQL"],"locations":["Toronto","Waterloo"],"salary_range":"$80K-$195K"},
    {"name":"Great-West Lifeco","careers_url":"https://jobs.canadalife.com/ca/en/search-results?keywords=data+engineer","category":"Banks","scraper":"phenom","top100":False,"titles":["Data Engineer","ETL Developer","Analytics Engineer"],"stack":["Azure","Python","SQL","Power BI"],"locations":["Winnipeg","Toronto"],"salary_range":"$78K-$185K"},
    {"name":"Intact Financial","careers_url":"https://intactfc.wd3.myworkdayjobs.com/intactfc","category":"Banks","scraper":"workday","top100":True,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["GCP","BigQuery","Python","dbt","Spark"],"locations":["Toronto","Montreal"],"salary_range":"$85K-$200K"},
    {"name":"Goldman Sachs Canada","careers_url":"https://www.goldmansachs.com/careers/search#ss=data+engineer&sl=Canada","category":"Banks","scraper":"custom","top100":True,"titles":["Senior Data Engineer","Data Infrastructure Engineer"],"stack":["Python","Spark","Kafka","SQL","GCP"],"locations":["Toronto"],"salary_range":"$140K-$220K"},
    {"name":"JP Morgan Canada","careers_url":"https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/requisitions?keyword=data+engineer&location=Toronto","category":"Banks","scraper":"oracle_hcm","top100":True,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["Python","Spark","AWS","SQL","Airflow"],"locations":["Toronto"],"salary_range":"$135K-$215K"},
    {"name":"Morgan Stanley Canada","careers_url":"https://morganstanley.wd3.myworkdayjobs.com/morganstanley?q=data+engineer&locationCountry=a30a87ed25634629aa6c3958aa2b91ea","category":"Banks","scraper":"workday","top100":False,"titles":["Data Engineer","Data Platform Engineer","Analytics Engineer"],"stack":["Python","AWS","Spark","SQL"],"locations":["Calgary","Toronto"],"salary_range":"$120K-$200K"},
    {"name":"Citibank Canada","careers_url":"https://jobs.citi.com/search-results?keywords=data+engineer&location=Canada","category":"Banks","scraper":"phenom","top100":False,"titles":["Senior Data Engineer","ETL Developer","Analytics Engineer"],"stack":["Azure","Python","SQL","Spark"],"locations":["Toronto","Mississauga"],"salary_range":"$100K-$185K"},
    {"name":"HSBC Canada","careers_url":"https://mycareer.hsbc.com/en_GB/external/search-results?keywords=data+engineer","category":"Banks","scraper":"phenom","top100":False,"titles":["Senior Data Engineer","BI Developer","Analytics Engineer"],"stack":["Azure","Python","SQL","Power BI"],"locations":["Toronto","Vancouver"],"salary_range":"$90K-$180K"},
    {"name":"Aviva Canada","careers_url":"https://www.aviva.ca/en/about-aviva/careers","category":"Banks","scraper":"custom","top100":False,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["Azure","Python","SQL","dbt"],"locations":["Toronto"],"salary_range":"$85K-$170K"},
    {"name":"Desjardins","careers_url":"https://desjardins.wd3.myworkdayjobs.com/DESJ?q=data+engineer&locationCountry=a30a87ed25634629aa6c3958aa2b91ea","category":"Banks","scraper":"workday","top100":True,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["Azure","Python","SQL","dbt","Spark"],"locations":["Montreal","Quebec City"],"salary_range":"$80K-$200K"},
    {"name":"CPP Investments","careers_url":"https://cppib.wd10.myworkdayjobs.com/cppinvestments?q=data+engineer&locationCountry=a30a87ed25634629aa6c3958aa2b91ea","category":"Banks","scraper":"workday","top100":False,"titles":["Senior Data Engineer","Analytics Engineer","Data Architect"],"stack":["Azure","GCP","Python","dbt","Spark"],"locations":["Toronto"],"salary_range":"$115K-$210K"},
    {"name":"Ontario Teachers Pension Plan","careers_url":"https://otppb.wd3.myworkdayjobs.com/OntarioTeachers_Careers?q=data+engineer&locationCountry=a30a87ed25634629aa6c3958aa2b91ea","category":"Banks","scraper":"workday","top100":False,"titles":["Senior Data Engineer","Analytics Engineer","Data Platform Engineer"],"stack":["GCP","Python","dbt","BigQuery","Spark"],"locations":["Toronto"],"salary_range":"$110K-$200K"},
    {"name":"Caisse de dépôt (CDPQ)","careers_url":"https://www.cdpq.com/en/about/careers","category":"Banks","scraper":"custom","top100":False,"titles":["Senior Data Engineer","Analytics Engineer","Data Architect"],"stack":["Azure","Python","SQL","dbt"],"locations":["Montreal"],"salary_range":"$110K-$200K"},

    # ══ FINTECH ══
    {"name":"Bloomberg Canada","careers_url":"https://bloomberg.avature.net/careers/SearchJobs/data%20engineer/Canada","category":"Fintech","scraper":"avature","top100":True,"titles":["Senior Software Engineer – Data","Data Engineer","Feeds Engineer"],"stack":["Python","C++","Kafka","Spark","AWS"],"locations":["Toronto"],"salary_range":"$155K-$260K"},
    {"name":"Wealthsimple","careers_url":"https://jobs.lever.co/wealthsimple?search=data+engineer","category":"Fintech","scraper":"lever","top100":True,"titles":["Senior Data Engineer","Data Platform Engineer","Analytics Engineer"],"stack":["GCP","BigQuery","dbt","Airflow","Python"],"locations":["Toronto","Remote"],"salary_range":"$128K-$212K"},
    {"name":"Capital One Canada","careers_url":"https://capitalone.wd12.myworkdayjobs.com/Capital_One?q=data+engineer&locationCountry=a30a87ed25634629aa6c3958aa2b91ea","category":"Fintech","scraper":"workday","top100":True,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["AWS","Spark","Python","Snowflake","dbt"],"locations":["Toronto"],"salary_range":"$128K-$218K"},
    {"name":"Visa Canada","careers_url":"https://jobs.smartrecruiters.com/Visa/search?keyword=data+engineer+canada","category":"Fintech","scraper":"smartrecruiters","top100":True,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["Azure","GCP","Spark","Python","SQL"],"locations":["Toronto","Vancouver"],"salary_range":"$130K-$210K"},
    {"name":"Mastercard Canada","careers_url":"https://mastercard.wd1.myworkdayjobs.com/CorporateCareers/jobs?q=data+engineer&locations=a30a87ed25634629aa6c3958aa2b91ea","category":"Fintech","scraper":"workday","top100":True,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["GCP","BigQuery","Python","dbt","Spark"],"locations":["Toronto"],"salary_range":"$125K-$200K"},
    {"name":"American Express Canada","careers_url":"https://careers.americanexpress.com/en/sites/CX_1/jobs","category":"Fintech","scraper":"oracle_hcm","top100":True,"titles":["Senior Data Engineer","Analytics Engineer","Data Scientist"],"stack":["AWS","Spark","Python","SQL","Airflow"],"locations":["Toronto"],"salary_range":"$120K-$210K"},
    {"name":"Stripe Canada","careers_url":"https://stripe.com/jobs/search?query=data+engineer&location=canada","category":"Fintech","scraper":"greenhouse","top100":True,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["GCP","BigQuery","dbt","Python","Spark"],"locations":["Remote Canada"],"salary_range":"$155K-$275K"},
    {"name":"Equifax Canada","careers_url":"https://equifax.wd1.myworkdayjobs.com/Equifax_External?q=data+engineer&locationCountry=a30a87ed25634629aa6c3958aa2b91ea","category":"Fintech","scraper":"workday","top100":True,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["Azure","AWS","Python","Spark","SQL"],"locations":["Toronto"],"salary_range":"$120K-$195K"},
    {"name":"PayPal Canada","careers_url":"https://www.paypal.com/ca/webapps/mpp/jobs","category":"Fintech","scraper":"custom","top100":False,"titles":["Senior Data Engineer","Data Platform Engineer"],"stack":["AWS","Spark","Flink","Python","Kafka"],"locations":["Remote Canada"],"salary_range":"$130K-$210K"},
    {"name":"Coinbase Canada","careers_url":"https://www.coinbase.com/careers","category":"Fintech","scraper":"greenhouse","top100":False,"titles":["Senior Data Engineer","Data Platform Engineer","Analytics Engineer"],"stack":["AWS","Spark","Python","dbt","Airflow"],"locations":["Remote Canada"],"salary_range":"$150K-$230K"},
    {"name":"Neo Financial","careers_url":"https://www.neofinancial.com/about/careers","category":"Fintech","scraper":"ashby","top100":False,"titles":["Data Engineer","Analytics Engineer","Senior Data Engineer"],"stack":["GCP","Python","dbt","BigQuery","SQL"],"locations":["Calgary","Remote"],"salary_range":"$100K-$170K"},
    {"name":"Questrade","careers_url":"https://www.questrade.com/about-us/careers","category":"Fintech","scraper":"custom","top100":False,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["Azure","Databricks","Python","SQL","dbt"],"locations":["Toronto"],"salary_range":"$110K-$175K"},
    {"name":"TransUnion Canada","careers_url":"https://transunion.wd5.myworkdayjobs.com/TransUnion?q=data+engineer&locationCountry=a30a87ed25634629aa6c3958aa2b91ea","category":"Fintech","scraper":"workday","top100":False,"titles":["Senior Data Engineer","Data Platform Engineer","Analytics Engineer"],"stack":["Azure","Python","Spark","SQL","dbt"],"locations":["Toronto"],"salary_range":"$110K-$185K"},
    {"name":"Wave Financial","careers_url":"https://jobs.lever.co/waveapps","category":"Fintech","scraper":"lever","top100":False,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["GCP","Python","dbt","BigQuery","Airflow"],"locations":["Toronto"],"salary_range":"$110K-$175K"},
    {"name":"Koho","careers_url":"https://www.koho.ca/careers","category":"Fintech","scraper":"ashby","top100":False,"titles":["Senior Data Engineer","Analytics Engineer","Data Platform Engineer"],"stack":["GCP","Python","dbt","BigQuery","Airflow"],"locations":["Toronto","Remote"],"salary_range":"$105K-$170K"},
    {"name":"Trulioo","careers_url":"https://www.trulioo.com/company/careers","category":"Fintech","scraper":"ashby","top100":False,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["GCP","Python","dbt","BigQuery"],"locations":["Vancouver"],"salary_range":"$100K-$165K"},
    {"name":"Finastra Canada","careers_url":"https://finastra.wd3.myworkdayjobs.com/FINC?q=data+engineer&locationCountry=a30a87ed25634629aa6c3958aa2b91ea","category":"Fintech","scraper":"workday","top100":False,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["Azure","Python","SQL","Spark","dbt"],"locations":["Toronto"],"salary_range":"$110K-$185K"},
    {"name":"Nuvei","careers_url":"https://www.nuvei.com/careers","category":"Fintech","scraper":"greenhouse","top100":False,"titles":["Data Engineer","Senior Data Engineer","Analytics Engineer"],"stack":["AWS","Python","Spark","SQL"],"locations":["Montreal","Toronto"],"salary_range":"$100K-$170K"},

    # ══ BIG TECH ══
    {"name":"Google Canada","careers_url":"https://careers.google.com/jobs/results/?q=data+engineer&location=Canada&employment_type=FULL_TIME","category":"Big Tech","scraper":"custom","top100":True,"titles":["Software Engineer Data Infrastructure","Technical Solutions Engineer","Analytics Engineer"],"stack":["GCP","BigQuery","Dataflow","Python","Go"],"locations":["Toronto","Waterloo","Montreal"],"salary_range":"$145K-$340K+"},
    {"name":"Microsoft Canada","careers_url":"https://jobs.careers.microsoft.com/global/en/search?q=data%20engineer&lc=Canada&l=en_us&pgSz=20&o=Recent","category":"Big Tech","scraper":"custom","top100":True,"titles":["Senior Data Engineer","Data Platform Engineer","Principal Data Engineer"],"stack":["Azure","Databricks","Fabric","Python","Spark"],"locations":["Toronto","Vancouver","Ottawa"],"salary_range":"$130K-$285K"},
    {"name":"Amazon / AWS Canada","careers_url":"https://www.amazon.jobs/en/search?base_query=data+engineer&loc_query=Canada&job_type=Full-Time","category":"Big Tech","scraper":"custom","top100":True,"titles":["Senior Data Engineer","Business Intelligence Engineer","Data Engineer II"],"stack":["AWS","Redshift","Glue","Python","Spark"],"locations":["Toronto","Vancouver"],"salary_range":"$118K-$248K"},
    {"name":"Meta Canada","careers_url":"https://www.metacareers.com/jobs?q=data+engineer&offices[]=Toronto%2C+ON","category":"Big Tech","scraper":"custom","top100":True,"titles":["Senior Data Engineer","Analytics Engineer","Data Infrastructure Engineer"],"stack":["Spark","Presto","Hive","Python","Airflow"],"locations":["Toronto"],"salary_range":"$140K-$270K"},
    {"name":"Apple Canada","careers_url":"https://jobs.apple.com/en-ca/search?search=data+engineer&sort=newest&location=canada-CAN","category":"Big Tech","scraper":"custom","top100":True,"titles":["Senior Data Engineer","ML Data Engineer","Data Infrastructure Engineer"],"stack":["Python","Spark","AWS","Kafka","SQL"],"locations":["Toronto","Vancouver"],"salary_range":"$165K-$275K"},
    {"name":"Netflix Canada","careers_url":"https://explore.jobs.netflix.net/careers?query=data+engineer&domain=netflix.com","category":"Big Tech","scraper":"custom","top100":True,"titles":["Senior Data Engineer","Senior SWE Data Platform","Analytics Engineer"],"stack":["Spark","Flink","Iceberg","Python","Maestro"],"locations":["Remote Canada"],"salary_range":"$195K-$295K"},
    {"name":"Shopify","careers_url":"https://www.shopify.com/careers","category":"Big Tech","scraper":"custom","top100":True,"titles":["Senior Data Engineer","Staff Data Engineer","Analytics Engineer"],"stack":["GCP","Trino","Spark","dbt","Python"],"locations":["Ottawa","Toronto","Remote"],"salary_range":"$120K-$262K"},
    {"name":"Uber Canada","careers_url":"https://www.uber.com/global/en/careers/list/?query=data+engineer&location=Toronto","category":"Big Tech","scraper":"custom","top100":True,"titles":["Senior SWE Data","Data Platform Engineer","Analytics Engineer"],"stack":["Flink","Kafka","Hudi","Python","Spark"],"locations":["Toronto"],"salary_range":"$165K-$275K"},
    {"name":"LinkedIn Canada","careers_url":"https://careers.linkedin.com/jobs?keywords=data+engineer&location=Canada","category":"Big Tech","scraper":"greenhouse","top100":True,"titles":["Senior Data Engineer","Analytics Engineer","Staff Data Engineer"],"stack":["Kafka","Samza","Spark","Python","Espresso"],"locations":["Toronto"],"salary_range":"$162K-$265K"},
    {"name":"Airbnb Canada","careers_url":"https://careers.airbnb.com/positions/?department=Engineering&location=Canada","category":"Big Tech","scraper":"greenhouse","top100":True,"titles":["Senior Data Engineer","Analytics Engineer","Staff Data Engineer"],"stack":["Spark","Airflow","dbt","Python","Presto"],"locations":["Remote Canada"],"salary_range":"$172K-$278K"},
    {"name":"Spotify Canada","careers_url":"https://jobs.lever.co/spotify?search=data+engineer&commitment=Full-Time","category":"Big Tech","scraper":"lever","top100":True,"titles":["Senior Data Engineer","Backend Engineer Data Platform","Analytics Engineer"],"stack":["GCP","BigQuery","Beam","Python","Scio"],"locations":["Remote Canada"],"salary_range":"$155K-$252K"},
    {"name":"Databricks Canada","careers_url":"https://www.databricks.com/company/careers/open-positions?department=All+Departments&location=Canada","category":"Big Tech","scraper":"greenhouse","top100":True,"titles":["Solutions Architect Data","Senior Data Engineer","Field Engineer"],"stack":["Databricks","Delta Lake","Spark","Unity Catalog","MLflow"],"locations":["Remote Canada"],"salary_range":"$152K-$260K"},
    {"name":"Snowflake Canada","careers_url":"https://careers.snowflake.com/jobs?search=data+engineer&location=Canada","category":"Big Tech","scraper":"lever","top100":True,"titles":["Solutions Engineer","Data Cloud Architect","Senior Data Engineer"],"stack":["Snowflake","Python","dbt","SQL","Airflow"],"locations":["Remote Canada"],"salary_range":"$155K-$248K"},
    {"name":"Confluent Canada","careers_url":"https://careers.confluent.io/jobs?search=data+engineer&location=Canada","category":"Big Tech","scraper":"ashby","top100":True,"titles":["Solutions Engineer","Data Streaming Engineer"],"stack":["Kafka","Flink","Python","Java","ksqlDB"],"locations":["Remote Canada"],"salary_range":"$155K-$245K"},
    {"name":"OpenAI Canada","careers_url":"https://openai.com/careers/search?q=data+engineer","category":"Big Tech","scraper":"ashby","top100":True,"titles":["Data Engineer","ML Data Engineer","Data Platform Engineer"],"stack":["AWS","Python","Spark","SQL","dbt"],"locations":["Toronto"],"salary_range":"$185K-$290K"},
    {"name":"Cohere AI","careers_url":"https://cohere.com/careers#open-roles","category":"Big Tech","scraper":"ashby","top100":True,"titles":["Senior Data Engineer","ML Data Engineer"],"stack":["GCP","Python","Spark","SQL","dbt"],"locations":["Toronto"],"salary_range":"$175K-$278K"},
    {"name":"Nvidia Canada","careers_url":"https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite/jobs?q=data+engineer&locationHierarchy1=2fcb99c455831013ea52fb338f2932d8","category":"Big Tech","scraper":"workday","top100":True,"titles":["Senior Data Engineer","ML Data Engineer","Principal Data Engineer"],"stack":["GCP","AWS","Python","Spark","CUDA"],"locations":["Toronto","Waterloo","Vancouver"],"salary_range":"$172K-$272K"},
    {"name":"Salesforce Canada","careers_url":"https://salesforce.wd12.myworkdayjobs.com/External_Career_Site/jobs?q=data+engineer&locationCountry=a30a87ed25634629aa6c3958aa2b91ea","category":"Big Tech","scraper":"workday","top100":True,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["GCP","Spark","Python","dbt","Tableau"],"locations":["Toronto","Vancouver"],"salary_range":"$130K-$225K"},
    {"name":"Atlassian Canada","careers_url":"https://www.atlassian.com/company/careers/all-jobs?team=Engineering&location=Canada","category":"Big Tech","scraper":"custom","top100":True,"titles":["Senior Data Engineer","Analytics Engineer","Data Platform Engineer"],"stack":["AWS","Spark","dbt","Python","Airflow"],"locations":["Remote Canada"],"salary_range":"$140K-$240K"},
    {"name":"Adobe Canada","careers_url":"https://adobe.wd5.myworkdayjobs.com/external_experienced/jobs?q=data+engineer&locationCountry=a30a87ed25634629aa6c3958aa2b91ea","category":"Big Tech","scraper":"workday","top100":True,"titles":["Senior Data Engineer","Analytics Engineer","Data Scientist"],"stack":["AWS","Spark","Python","SQL","Airflow"],"locations":["Toronto","Vancouver"],"salary_range":"$130K-$230K"},
    {"name":"Intuit Canada","careers_url":"https://jobs.intuit.com/search-jobs?k=data+engineer&l=Canada","category":"Big Tech","scraper":"custom","top100":True,"titles":["Senior Data Engineer","Principal Data Engineer"],"stack":["AWS","Spark","Python","dbt","Airflow"],"locations":["Toronto","Montreal"],"salary_range":"$130K-$220K"},
    {"name":"Workday Canada","careers_url":"https://workday.wd5.myworkdayjobs.com/Workday/jobs?q=data+engineer&locationCountry=a30a87ed25634629aa6c3958aa2b91ea","category":"Big Tech","scraper":"workday","top100":True,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["Snowflake","Python","dbt","AWS","Spark"],"locations":["Vancouver","Toronto"],"salary_range":"$140K-$230K"},
    {"name":"ServiceNow Canada","careers_url":"https://jobs.smartrecruiters.com/ServiceNow/search?keyword=data+engineer+canada","category":"Big Tech","scraper":"smartrecruiters","top100":True,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["AWS","Snowflake","Python","dbt","Spark"],"locations":["Toronto","Vancouver"],"salary_range":"$140K-$235K"},
    {"name":"Autodesk Canada","careers_url":"https://autodesk.wd1.myworkdayjobs.com/Ext/jobs?q=data+engineer&locationCountry=a30a87ed25634629aa6c3958aa2b91ea","category":"Big Tech","scraper":"workday","top100":True,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["GCP","BigQuery","Python","dbt","Spark"],"locations":["Toronto","Vancouver","Montreal"],"salary_range":"$130K-$215K"},
    {"name":"Canva Canada","careers_url":"https://www.canva.com/careers","category":"Big Tech","scraper":"greenhouse","top100":True,"titles":["Senior Data Engineer","Analytics Engineer","Data Platform Engineer"],"stack":["GCP","BigQuery","Python","dbt","Airflow"],"locations":["Remote Canada"],"salary_range":"$140K-$240K"},
    {"name":"Unity Technologies Canada","careers_url":"https://boards.greenhouse.io/unity3d","category":"Big Tech","scraper":"greenhouse","top100":True,"titles":["Senior Data Engineer","Analytics Engineer","Data Platform Engineer"],"stack":["GCP","BigQuery","Python","dbt","Spark"],"locations":["Montreal","Toronto"],"salary_range":"$130K-$215K"},
    {"name":"Electronic Arts Canada","careers_url":"https://www.ea.com/careers","category":"Big Tech","scraper":"smartrecruiters","top100":True,"titles":["Senior Data Engineer","Analytics Engineer","Data Scientist"],"stack":["AWS","Spark","Python","dbt","SQL"],"locations":["Vancouver","Burnaby"],"salary_range":"$120K-$210K"},
    {"name":"Tesla Canada","careers_url":"https://www.tesla.com/careers/search?query=data+engineer&location=Canada","category":"Big Tech","scraper":"custom","top100":True,"titles":["Senior Data Engineer","Data Platform Engineer","ML Data Engineer"],"stack":["Python","Spark","AWS","SQL","Kafka"],"locations":["Toronto","Vancouver"],"salary_range":"$140K-$230K"},
    {"name":"Oracle Canada","careers_url":"https://www.oracle.com/ca-en/corporate/careers","category":"Big Tech","scraper":"custom","top100":False,"titles":["Senior Data Engineer","Cloud Data Architect","ETL Developer"],"stack":["OCI","Oracle DB","Python","Spark","SQL"],"locations":["Toronto","Ottawa","Mississauga"],"salary_range":"$110K-$190K"},
    {"name":"Hootsuite","careers_url":"https://www.hootsuite.com/company/careers","category":"Big Tech","scraper":"greenhouse","top100":False,"titles":["Senior Data Engineer","Analytics Engineer","Data Platform Engineer"],"stack":["GCP","BigQuery","Python","dbt","Spark"],"locations":["Vancouver","Toronto"],"salary_range":"$110K-$190K"},
    {"name":"DoorDash Canada","careers_url":"https://careers.doordash.com","category":"Big Tech","scraper":"greenhouse","top100":False,"titles":["Senior Data Engineer","Staff Data Engineer","Analytics Engineer"],"stack":["Kafka","Spark","Flink","Python","dbt"],"locations":["Toronto","Remote"],"salary_range":"$150K-$250K"},
    {"name":"Reddit Canada","careers_url":"https://www.reddit.com/r/redditjobs","category":"Big Tech","scraper":"greenhouse","top100":False,"titles":["Data Engineer","Senior Data Engineer","Analytics Engineer"],"stack":["GCP","BigQuery","Python","dbt","Airflow"],"locations":["Remote Canada"],"salary_range":"$140K-$230K"},
    {"name":"Dropbox Canada","careers_url":"https://jobs.dropbox.com","category":"Big Tech","scraper":"greenhouse","top100":False,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["AWS","Python","dbt","Airflow","Spark"],"locations":["Remote Canada"],"salary_range":"$140K-$225K"},
    {"name":"Pinterest Canada","careers_url":"https://www.pinterestcareers.com","category":"Big Tech","scraper":"greenhouse","top100":False,"titles":["Senior Data Engineer","Analytics Engineer","Data Platform Engineer"],"stack":["AWS","Spark","Python","dbt","Airflow"],"locations":["Remote Canada"],"salary_range":"$140K-$230K"},
    {"name":"Lyft Canada","careers_url":"https://www.lyft.com/careers","category":"Big Tech","scraper":"greenhouse","top100":False,"titles":["Senior Data Engineer","Data Platform Engineer","Analytics Engineer"],"stack":["Spark","Flink","Python","dbt"],"locations":["Remote Canada"],"salary_range":"$145K-$235K"},
    {"name":"HubSpot Canada","careers_url":"https://www.hubspot.com/careers","category":"Big Tech","scraper":"greenhouse","top100":False,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["AWS","Python","dbt","Spark","Airflow"],"locations":["Remote Canada"],"salary_range":"$130K-$215K"},
    {"name":"Twilio Canada","careers_url":"https://www.twilio.com/company/jobs","category":"Big Tech","scraper":"greenhouse","top100":False,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["Snowflake","dbt","Python","Airflow"],"locations":["Remote Canada"],"salary_range":"$130K-$215K"},
    {"name":"Cloudflare Canada","careers_url":"https://www.cloudflare.com/careers","category":"Big Tech","scraper":"greenhouse","top100":False,"titles":["Senior Data Engineer","Data Platform Engineer"],"stack":["ClickHouse","Python","Go","Kafka"],"locations":["Remote Canada"],"salary_range":"$140K-$225K"},
    {"name":"BlackBerry Canada","careers_url":"https://bb.wd3.myworkdayjobs.com/BlackBerry?q=data+engineer&locationCountry=a30a87ed25634629aa6c3958aa2b91ea","category":"Big Tech","scraper":"workday","top100":False,"titles":["Senior Data Engineer","Data Platform Engineer"],"stack":["AWS","Python","SQL","Spark"],"locations":["Waterloo","Ottawa"],"salary_range":"$100K-$175K"},
    {"name":"CrowdStrike Canada","careers_url":"https://crowdstrike.wd5.myworkdayjobs.com/crowdstrikecareers?q=data+engineer&locationCountry=a30a87ed25634629aa6c3958aa2b91ea","category":"Big Tech","scraper":"workday","top100":False,"titles":["Senior Data Engineer","Data Platform Engineer","Analytics Engineer"],"stack":["AWS","Python","Spark","Kafka"],"locations":["Remote Canada"],"salary_range":"$140K-$230K"},
    {"name":"Palo Alto Networks Canada","careers_url":"https://paloaltonetworks.wd5.myworkdayjobs.com/panwexternalcareers?q=data+engineer&locationCountry=a30a87ed25634629aa6c3958aa2b91ea","category":"Big Tech","scraper":"workday","top100":False,"titles":["Senior Data Engineer","Data Platform Engineer","Analytics Engineer"],"stack":["GCP","Python","Spark","SQL","dbt"],"locations":["Toronto","Vancouver"],"salary_range":"$140K-$235K"},

    # ══ DATA & ANALYTICS VENDORS ══
    {"name":"dbt Labs Canada","careers_url":"https://www.getdbt.com/about-us/careers","category":"Data & Analytics","scraper":"greenhouse","top100":True,"titles":["Senior Data Engineer","Analytics Engineer","Solutions Architect"],"stack":["dbt","Snowflake","BigQuery","Python","SQL"],"locations":["Remote Canada"],"salary_range":"$145K-$215K"},
    {"name":"Fivetran Canada","careers_url":"https://www.fivetran.com/careers","category":"Data & Analytics","scraper":"greenhouse","top100":True,"titles":["Senior Data Engineer","Solutions Engineer"],"stack":["Fivetran","Python","SQL","dbt","Snowflake"],"locations":["Remote Canada"],"salary_range":"$155K-$205K"},
    {"name":"Palantir Canada","careers_url":"https://jobs.lever.co/palantir","category":"Data & Analytics","scraper":"lever","top100":True,"titles":["Forward Deployed Engineer","Data Engineer"],"stack":["Foundry","Python","Spark","Java","Ontology"],"locations":["Toronto"],"salary_range":"$155K-$260K"},
    {"name":"Datadog Canada","careers_url":"https://www.datadoghq.com/careers/detail/?gh_jid=&location=Canada","category":"Data & Analytics","scraper":"greenhouse","top100":True,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["AWS","Python","Spark","Go","SQL"],"locations":["Toronto","Remote"],"salary_range":"$140K-$220K"},
    {"name":"Veeva Systems Canada","careers_url":"https://jobs.lever.co/veeva?search=data+engineer","category":"Data & Analytics","scraper":"lever","top100":True,"titles":["Senior Data Engineer","Data Platform Engineer"],"stack":["Spark","Python","AWS","SQL","dbt"],"locations":["Remote Canada"],"salary_range":"$130K-$210K"},
    {"name":"Elastic Canada","careers_url":"https://jobs.elastic.co/jobs","category":"Data & Analytics","scraper":"greenhouse","top100":False,"titles":["Senior Data Engineer","Solutions Architect"],"stack":["Elasticsearch","Python","AWS","Kafka"],"locations":["Remote Canada"],"salary_range":"$130K-$200K"},
    {"name":"MongoDB Canada","careers_url":"https://www.mongodb.com/careers/search?q=data+engineer&location=Canada","category":"Data & Analytics","scraper":"greenhouse","top100":False,"titles":["Senior Data Engineer","Solutions Architect"],"stack":["MongoDB","Python","AWS","SQL"],"locations":["Toronto","Remote"],"salary_range":"$130K-$205K"},
    {"name":"Airbyte Canada","careers_url":"https://airbyte.com/careers","category":"Data & Analytics","scraper":"ashby","top100":False,"titles":["Senior Data Engineer","Solutions Engineer"],"stack":["Airbyte","Python","dbt","SQL"],"locations":["Remote Canada"],"salary_range":"$140K-$220K"},
    {"name":"Astronomer Canada","careers_url":"https://www.astronomer.io/careers","category":"Data & Analytics","scraper":"ashby","top100":False,"titles":["Solutions Architect","Senior Data Engineer","Field Engineer"],"stack":["Airflow","Python","GCP","AWS","dbt"],"locations":["Remote Canada"],"salary_range":"$130K-$210K"},
    {"name":"Splunk Canada","careers_url":"https://careers.cisco.com/global/en/search-results?keywords=data+engineer","category":"Data & Analytics","scraper":"phenom","top100":False,"titles":["Senior Data Engineer","Data Platform Engineer"],"stack":["AWS","Python","Spark","SQL","Kafka"],"locations":["Toronto","Vancouver"],"salary_range":"$130K-$215K"},


    # ══ TELECOM (Bell only) ══
    {"name":"Bell Canada","careers_url":"https://jobs.bell.ca/ca/en/search-results?keywords=data+engineer","category":"Telecom","scraper":"phenom","top100":True,"titles":["Senior Data Engineer","ETL Developer","Analytics Engineer"],"stack":["Azure","Python","Spark","SQL","ADF"],"locations":["Toronto","Montreal"],"salary_range":"$80K-$210K"},

    # ══ CONSULTING ══
    {"name":"Accenture Canada","careers_url":"https://accenture.wd103.myworkdayjobs.com/AccentureCareers?q=data+engineer&locationCountry=a30a87ed25634629aa6c3958aa2b91ea","category":"Consulting","scraper":"workday","top100":True,"titles":["Data Engineer Analyst","Senior Data Engineer","Cloud Data Engineer","Analytics Engineer"],"stack":["Azure","AWS","GCP","Spark","Python"],"locations":["Toronto","Montreal","Vancouver","Ottawa"],"salary_range":"$75K-$225K"},
    {"name":"Deloitte Canada","careers_url":"https://careers.deloitte.ca/search-results?keywords=data+engineer&location=Canada&locale=en_US","category":"Consulting","scraper":"custom","top100":True,"titles":["Data Engineer Analyst","Senior Data Engineer","Cloud Data Engineer","Analytics Engineer"],"stack":["Azure","Databricks","Python","Spark","dbt"],"locations":["Toronto","Montreal","Calgary","Vancouver"],"salary_range":"$75K-$290K"},
    {"name":"PwC Canada","careers_url":"https://pwc.wd3.myworkdayjobs.com/Global_Campus_Careers?q=data+engineer","category":"Consulting","scraper":"workday","top100":True,"titles":["Data Engineer Associate","Senior Data Engineer","Analytics Engineer"],"stack":["Azure","AWS","Python","dbt","Spark"],"locations":["Toronto","Vancouver","Calgary"],"salary_range":"$75K-$215K"},
    {"name":"EY Canada","careers_url":"https://jobs.smartrecruiters.com/EY/search?keyword=data+engineer+canada","category":"Consulting","scraper":"smartrecruiters","top100":True,"titles":["Senior Data Engineer","Analytics Engineer","Cloud Data Engineer"],"stack":["Azure","AWS","GCP","Python","Spark"],"locations":["Toronto","Montreal","Vancouver"],"salary_range":"$74K-$208K"},
    {"name":"McKinsey Canada","careers_url":"https://jobs.smartrecruiters.com/McKinsey/search?keyword=data+engineer+canada","category":"Consulting","scraper":"smartrecruiters","top100":True,"titles":["Senior Data Engineer","QuantumBlack Data Engineer"],"stack":["GCP","Python","Spark","dbt","SQL"],"locations":["Toronto","Montreal"],"salary_range":"$110K-$238K"},
    {"name":"IBM Canada","careers_url":"https://careers.ibm.com/en_US/careers/search?q=data+engineer&location=Canada","category":"Consulting","scraper":"custom","top100":True,"titles":["Senior Data Engineer","Analytics Engineer","DataOps Engineer"],"stack":["IBM Cloud","AWS","Python","Spark","SQL"],"locations":["Toronto","Ottawa","Montreal"],"salary_range":"$80K-$215K"},
    {"name":"CGI Group","careers_url":"https://jobs.smartrecruiters.com/CGI/search?keyword=data+engineer+canada","category":"Consulting","scraper":"smartrecruiters","top100":True,"titles":["Senior Data Engineer","ETL Developer","Analytics Engineer","BI Developer"],"stack":["Azure","AWS","Python","Spark","SQL"],"locations":["Toronto","Ottawa","Montreal","Vancouver"],"salary_range":"$78K-$202K"},
    {"name":"KPMG Canada","careers_url":"https://jobs.smartrecruiters.com/KPMG/search?keyword=data+engineer+canada","category":"Consulting","scraper":"smartrecruiters","top100":True,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["Azure","AWS","Python","Spark","SQL"],"locations":["Toronto","Vancouver","Calgary"],"salary_range":"$80K-$200K"},
    {"name":"Capgemini Canada","careers_url":"https://www.capgemini.com/ca-en/jobs/search-results?keywords=data+engineer&locale=en_US","category":"Consulting","scraper":"custom","top100":False,"titles":["Senior Data Engineer","Big Data Engineer"],"stack":["Azure","AWS","Python","Spark","SQL"],"locations":["Toronto","Montreal"],"salary_range":"$85K-$185K"},
    {"name":"TCS Canada","careers_url":"https://ibegin.tcsapps.com/candidate/jobs?searchTerm=data+engineer&countryId=38","category":"Consulting","scraper":"custom","top100":False,"titles":["Senior Data Engineer","Cloud Data Engineer"],"stack":["Azure","AWS","Python","Spark","SQL"],"locations":["Toronto","Vancouver","Calgary"],"salary_range":"$85K-$175K"},
    {"name":"Wipro Canada","careers_url":"https://careers.wipro.com/search-results?keywords=data+engineer&location=Canada&locale=en_US","category":"Consulting","scraper":"custom","top100":False,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["Azure","AWS","Python","Spark","SQL"],"locations":["Toronto","Vancouver"],"salary_range":"$85K-$168K"},
    {"name":"Infosys Canada","careers_url":"https://career.infosys.com/joblist?search=data+engineer&location=Canada","category":"Consulting","scraper":"custom","top100":False,"titles":["Senior Data Engineer","Data Architect"],"stack":["Azure","AWS","Python","Spark","SQL"],"locations":["Toronto","Vancouver","Montreal"],"salary_range":"$85K-$170K"},
    {"name":"Cognizant Canada","careers_url":"https://careers.cognizant.com/ca-en/jobs?search=data+engineer","category":"Consulting","scraper":"custom","top100":False,"titles":["Senior Data Engineer","Cloud Data Engineer"],"stack":["Azure","AWS","Python","Spark"],"locations":["Toronto","Montreal"],"salary_range":"$85K-$170K"},
    {"name":"Stantec","careers_url":"https://www.stantec.com/en/careers","category":"Consulting","scraper":"custom","top100":False,"titles":["Senior Data Engineer","Analytics Engineer","Data Architect"],"stack":["Azure","GCP","Python","SQL","dbt"],"locations":["Edmonton","Calgary","Toronto"],"salary_range":"$95K-$175K"},
    {"name":"WSP Global","careers_url":"https://www.wsp.com/en-CA/careers","category":"Consulting","scraper":"custom","top100":False,"titles":["Senior Data Engineer","Analytics Engineer","Data Architect"],"stack":["Azure","Python","SQL","dbt","Power BI"],"locations":["Montreal","Toronto","Vancouver"],"salary_range":"$90K-$175K"},

    # ══ HEALTHCARE ══
    {"name":"Ontario Health","careers_url":"https://ehealthontario.wd3.myworkdayjobs.com/OntarioHealth/jobs?q=data+engineer","category":"Healthcare","scraper":"workday","top100":True,"titles":["Senior Data Engineer","Health Data Engineer","Analytics Engineer"],"stack":["Azure","Python","SQL","Power BI","ADF"],"locations":["Toronto","Ottawa"],"salary_range":"$80K-$200K"},
    {"name":"PointClickCare","careers_url":"https://jobs.lever.co/pointclickcare?search=data+engineer","category":"Healthcare","scraper":"lever","top100":True,"titles":["Senior Data Engineer","Analytics Engineer","Principal Data Engineer"],"stack":["Azure","Databricks","Python","SQL","dbt"],"locations":["Mississauga","Toronto"],"salary_range":"$112K-$188K"},
    {"name":"TELUS Health","careers_url":"https://careers.telus.com/search-results?keywords=data+engineer&location=Canada&locale=en_US","category":"Healthcare","scraper":"custom","top100":True,"titles":["Senior Data Engineer","Healthcare Data Engineer"],"stack":["GCP","Python","dbt","BigQuery","Airflow"],"locations":["Vancouver","Toronto","Remote"],"salary_range":"$110K-$195K"},
    {"name":"WELL Health Technologies","careers_url":"https://well.ca/careers","category":"Healthcare","scraper":"custom","top100":False,"titles":["Senior Data Engineer","Analytics Engineer","Data Platform Engineer"],"stack":["Snowflake","Python","dbt","AWS","Airflow"],"locations":["Vancouver","Remote"],"salary_range":"$100K-$170K"},
    {"name":"Roche Canada","careers_url":"https://careers.roche.com/global/en/search-results?keywords=data+engineer&location=Canada","category":"Healthcare","scraper":"phenom","top100":False,"titles":["Data Engineer","Senior Data Engineer","Data Scientist"],"stack":["AWS","Python","Spark","SQL","R"],"locations":["Toronto","Mississauga"],"salary_range":"$100K-$175K"},
    {"name":"LifeLabs","careers_url":"https://www.lifelabs.com/careers","category":"Healthcare","scraper":"custom","top100":False,"titles":["Data Engineer","Senior Data Engineer","BI Developer"],"stack":["Azure","Python","SQL","Power BI"],"locations":["Toronto","Vancouver"],"salary_range":"$85K-$155K"},
    {"name":"League Inc","careers_url":"https://league.com/careers","category":"Healthcare","scraper":"greenhouse","top100":False,"titles":["Senior Data Engineer","Analytics Engineer","Data Platform Engineer"],"stack":["GCP","Python","dbt","BigQuery"],"locations":["Toronto","Remote"],"salary_range":"$115K-$185K"},
    {"name":"Phreesia Canada","careers_url":"https://phreesia.wd1.myworkdayjobs.com/PhreesiaCanada?q=data+engineer&locationCountry=a30a87ed25634629aa6c3958aa2b91ea","category":"Healthcare","scraper":"workday","top100":False,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["AWS","Python","dbt","Airflow"],"locations":["Remote Canada"],"salary_range":"$120K-$190K"},

    # ══ RETAIL & E-COMMERCE ══
    {"name":"Loblaw Companies","careers_url":"https://loblaw.wd3.myworkdayjobs.com/loblaw/jobs?q=data+engineer","category":"Retail","scraper":"workday","top100":True,"titles":["Senior Data Engineer","Data Platform Engineer","Analytics Engineer"],"stack":["GCP","BigQuery","Python","dbt","Airflow"],"locations":["Toronto","Brampton"],"salary_range":"$82K-$212K"},
    {"name":"Walmart Canada","careers_url":"https://walmart.wd5.myworkdayjobs.com/WalmartExternal/jobs?q=data+engineer&locationCountry=a30a87ed25634629aa6c3958aa2b91ea","category":"Retail","scraper":"workday","top100":True,"titles":["Senior Data Engineer","Data Platform Engineer","Analytics Engineer"],"stack":["Azure","GCP","Spark","Python","SQL"],"locations":["Mississauga","Toronto"],"salary_range":"$118K-$210K"},
    {"name":"Canadian Tire Corporation","careers_url":"https://canadiantirecorporation.wd3.myworkdayjobs.com/Enterprise_External_Careers_Site?q=data+engineer&locationCountry=a30a87ed25634629aa6c3958aa2b91ea","category":"Retail","scraper":"workday","top100":True,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["Azure","Databricks","Python","SQL","dbt"],"locations":["Toronto"],"salary_range":"$115K-$208K"},
    {"name":"Lululemon Canada","careers_url":"https://jobs.smartrecruiters.com/lululemon/search?keyword=data+engineer+canada","category":"Retail","scraper":"smartrecruiters","top100":True,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["GCP","BigQuery","Python","dbt","Airflow"],"locations":["Vancouver"],"salary_range":"$120K-$195K"},
    {"name":"Wayfair Canada","careers_url":"https://www.wayfair.com/careers/jobs?country=Canada&query=data+engineer","category":"Retail","scraper":"custom","top100":True,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["GCP","BigQuery","Python","dbt","Airflow"],"locations":["Toronto"],"salary_range":"$120K-$195K"},
    {"name":"Restaurant Brands International","careers_url":"https://careers.rbi.com/global/en/search-results?keywords=data+engineer","category":"Retail","scraper":"phenom","top100":True,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["Azure","Python","SQL","dbt","Spark"],"locations":["Toronto"],"salary_range":"$115K-$190K"},
    {"name":"Air Canada","careers_url":"https://careers.aircanada.com/ca/en/search-results?keywords=data+engineer","category":"Retail","scraper":"phenom","top100":True,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["Azure","GCP","Python","SQL","dbt"],"locations":["Montreal","Toronto"],"salary_range":"$110K-$190K"},
    {"name":"Sobeys / Empire","careers_url":"https://www.sobeys.com/en/careers","category":"Retail","scraper":"custom","top100":False,"titles":["Data Engineer","Senior Data Engineer","BI Developer"],"stack":["Azure","Python","SQL","Power BI"],"locations":["Stellarton NS","Toronto"],"salary_range":"$85K-$165K"},
    {"name":"WestJet","careers_url":"https://www.westjet.com/en-ca/about-westjet/careers","category":"Retail","scraper":"custom","top100":False,"titles":["Data Engineer","Senior Data Engineer","Analytics Engineer"],"stack":["Azure","Python","SQL","Power BI","dbt"],"locations":["Calgary"],"salary_range":"$90K-$168K"},
    {"name":"Best Buy Canada","careers_url":"https://bestbuycanada.wd3.myworkdayjobs.com/BestBuyCA_Career?q=data+engineer&locationCountry=a30a87ed25634629aa6c3958aa2b91ea","category":"Retail","scraper":"workday","top100":False,"titles":["Data Engineer","Senior Data Engineer","Analytics Engineer"],"stack":["Azure","Python","SQL","dbt","Spark"],"locations":["Vancouver","Toronto"],"salary_range":"$90K-$170K"},
    {"name":"Flipp","careers_url":"https://www.flipp.com/careers","category":"Retail","scraper":"greenhouse","top100":False,"titles":["Senior Data Engineer","Analytics Engineer","Data Platform Engineer"],"stack":["GCP","BigQuery","Python","dbt","Spark"],"locations":["Toronto"],"salary_range":"$110K-$185K"},
    {"name":"Faire","careers_url":"https://www.faire.com/careers","category":"Retail","scraper":"greenhouse","top100":False,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["Snowflake","Python","dbt","Airflow"],"locations":["Remote Canada"],"salary_range":"$130K-$210K"},

    # ══ GOVERNMENT ══
    {"name":"Government of Canada","careers_url":"https://www.canada.ca/en/services/jobs/opportunities/government.html","category":"Government","scraper":"custom","top100":True,"titles":["Data Engineer IT-02","Senior Data Engineer IT-04","Cloud Data Engineer"],"stack":["Azure","AWS","Python","SQL","Power BI"],"locations":["Ottawa","Toronto","Montreal"],"salary_range":"$75K-$175K"},
    {"name":"Statistics Canada","careers_url":"https://www.statcan.gc.ca/en/about/jobs","category":"Government","scraper":"custom","top100":True,"titles":["Data Engineer EC-04","Senior Data Engineer EC-06","Analytics Engineer"],"stack":["Azure","Python","R","SQL","Spark"],"locations":["Ottawa","Toronto"],"salary_range":"$78K-$170K"},
    {"name":"Bank of Canada","careers_url":"https://careers.bankofcanada.ca/search/?q=data+engineer","category":"Government","scraper":"custom","top100":True,"titles":["Senior Data Engineer","Cloud Data Engineer","Analytics Engineer"],"stack":["Azure","AWS","Python","Spark","SQL"],"locations":["Ottawa","Toronto"],"salary_range":"$110K-$198K"},
    {"name":"Export Development Canada","careers_url":"https://edc.wd3.myworkdayjobs.com/EDC_Careers/jobs?q=data+engineer","category":"Government","scraper":"workday","top100":True,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["AWS","Python","Spark","dbt","SQL"],"locations":["Ottawa","Toronto"],"salary_range":"$110K-$195K"},
    {"name":"City of Toronto","careers_url":"https://jobs.toronto.ca/jobsatcity/search/?q=data","category":"Government","scraper":"custom","top100":False,"titles":["Data Engineer","Analytics Engineer","BI Developer"],"stack":["Azure","Python","SQL","Power BI"],"locations":["Toronto"],"salary_range":"$85K-$155K"},
    {"name":"Ontario Digital Service","careers_url":"https://www.ontario.ca/page/ontario-digital-service","category":"Government","scraper":"custom","top100":False,"titles":["Senior Data Engineer","Cloud Data Engineer","Analytics Engineer"],"stack":["Azure","GCP","Python","SQL","dbt"],"locations":["Toronto","Ottawa"],"salary_range":"$90K-$165K"},
    {"name":"PSP Investments","careers_url":"https://www.investpsp.ca/en/careers","category":"Government","scraper":"custom","top100":False,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["Azure","Python","SQL","dbt","Airflow"],"locations":["Montreal","Ottawa"],"salary_range":"$110K-$195K"},

    # ══ STARTUPS & SCALE-UPS ══
    {"name":"Thomson Reuters","careers_url":"https://thomsonreuters.wd5.myworkdayjobs.com/External_Career_Site/jobs?q=data+engineer","category":"Startups","scraper":"workday","top100":True,"titles":["Senior Data Engineer","Analytics Engineer","Principal Data Engineer"],"stack":["GCP","AWS","Python","Spark","dbt"],"locations":["Toronto"],"salary_range":"$125K-$205K"},
    {"name":"Ceridian / Dayforce","careers_url":"https://ceridian.wd3.myworkdayjobs.com/ceridian/jobs?q=data+engineer","category":"Startups","scraper":"workday","top100":True,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["Azure","Python","SQL","dbt","Spark"],"locations":["Toronto","Winnipeg"],"salary_range":"$115K-$185K"},
    {"name":"Kinaxis","careers_url":"https://www.kinaxis.com/en/careers","category":"Startups","scraper":"custom","top100":True,"titles":["Senior Data Engineer","Analytics Engineer","Data Platform Engineer"],"stack":["AWS","Python","SQL","dbt","Airflow"],"locations":["Ottawa","Remote"],"salary_range":"$118K-$158K"},
    {"name":"Clio","careers_url":"https://www.clio.com/careers","category":"Startups","scraper":"custom","top100":True,"titles":["Senior Data Engineer","Analytics Engineer","Staff Data Engineer"],"stack":["GCP","BigQuery","Python","dbt","Airflow"],"locations":["Burnaby BC","Toronto","Remote"],"salary_range":"$120K-$200K"},
    {"name":"Geotab","careers_url":"https://www.geotab.com/careers","category":"Startups","scraper":"greenhouse","top100":True,"titles":["Senior Data Engineer","Data Platform Engineer","Analytics Engineer"],"stack":["GCP","BigQuery","Python","dbt","Airflow"],"locations":["Oakville ON","Remote"],"salary_range":"$120K-$180K"},
    {"name":"Borealis AI (RBC)","careers_url":"https://www.borealisai.com/careers","category":"Startups","scraper":"greenhouse","top100":True,"titles":["Senior ML Data Engineer","Data Platform Engineer","Research Data Engineer"],"stack":["GCP","Python","Spark","SQL","PyTorch"],"locations":["Toronto","Vancouver","Edmonton"],"salary_range":"$140K-$192K"},
    {"name":"Lightspeed Commerce","careers_url":"https://www.lightspeedhq.com/careers","category":"Startups","scraper":"ashby","top100":True,"titles":["Senior Data Engineer","Analytics Engineer","Data Platform Engineer"],"stack":["GCP","BigQuery","Python","dbt","Airflow"],"locations":["Montreal","Toronto"],"salary_range":"$120K-$165K"},
    {"name":"Coveo","careers_url":"https://www.coveo.com/en/company/careers","category":"Startups","scraper":"custom","top100":True,"titles":["Senior Data Engineer","Analytics Engineer","ML Data Engineer"],"stack":["GCP","BigQuery","Python","dbt","Spark"],"locations":["Quebec City","Toronto","Remote"],"salary_range":"$118K-$168K"},
    {"name":"Layer6 AI (TD)","careers_url":"https://td.wd3.myworkdayjobs.com/TD_Bank_Careers?q=data+engineer&locationCountry=a30a87ed25634629aa6c3958aa2b91ea","category":"Startups","scraper":"workday","top100":True,"titles":["Senior ML Data Engineer","Data Platform Engineer"],"stack":["GCP","AWS","Python","Spark","SQL"],"locations":["Toronto"],"salary_range":"$142K-$195K"},
    {"name":"Scotiabank Digital Factory","careers_url":"https://jobs.scotiabank.com/search-results?keywords=data+engineer+digital+factory&location=Canada&locale=en_US","category":"Startups","scraper":"custom","top100":True,"titles":["Senior Data Engineer","Data Platform Engineer","Analytics Engineer"],"stack":["GCP","Python","dbt","BigQuery"],"locations":["Toronto"],"salary_range":"$115K-$195K"},
    {"name":"OpenText","careers_url":"https://opentext.wd1.myworkdayjobs.com/careers/jobs?q=data+engineer","category":"Startups","scraper":"workday","top100":False,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["Azure","AWS","Python","Spark"],"locations":["Waterloo","Toronto"],"salary_range":"$110K-$185K"},
    {"name":"D2L / Desire2Learn","careers_url":"https://www.d2l.com/careers","category":"Startups","scraper":"greenhouse","top100":False,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["Azure","Python","SQL","dbt","Airflow"],"locations":["Kitchener-Waterloo"],"salary_range":"$105K-$170K"},
    {"name":"Jobber","careers_url":"https://getjobber.com/about/careers","category":"Startups","scraper":"custom","top100":False,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["GCP","Python","dbt","BigQuery"],"locations":["Edmonton","Remote"],"salary_range":"$110K-$165K"},
    {"name":"TouchBistro","careers_url":"https://www.touchbistro.com/careers","category":"Startups","scraper":"greenhouse","top100":False,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["GCP","BigQuery","Python","dbt"],"locations":["Toronto"],"salary_range":"$105K-$170K"},
    {"name":"Benevity","careers_url":"https://www.benevity.com/careers","category":"Startups","scraper":"greenhouse","top100":False,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["GCP","Python","dbt","BigQuery"],"locations":["Calgary","Toronto"],"salary_range":"$110K-$175K"},
    {"name":"Ecobee","careers_url":"https://www.ecobee.com/en-ca/careers","category":"Startups","scraper":"greenhouse","top100":False,"titles":["Data Engineer","Senior Data Engineer"],"stack":["GCP","Python","SQL","dbt","BigQuery"],"locations":["Toronto"],"salary_range":"$100K-$170K"},
    {"name":"Ritual","careers_url":"https://ritual.co/careers","category":"Startups","scraper":"greenhouse","top100":False,"titles":["Data Engineer","Senior Data Engineer","Analytics Engineer"],"stack":["GCP","Python","dbt","BigQuery","SQL"],"locations":["Toronto"],"salary_range":"$100K-$175K"},
    {"name":"Miovision Technologies","careers_url":"https://miovision.com/careers","category":"Startups","scraper":"custom","top100":False,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["AWS","Python","SQL","dbt"],"locations":["Kitchener-Waterloo"],"salary_range":"$100K-$165K"},
    {"name":"Top Hat","careers_url":"https://tophat.com/careers","category":"Startups","scraper":"custom","top100":False,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["AWS","Python","SQL","dbt"],"locations":["Toronto","Remote"],"salary_range":"$100K-$165K"},
    {"name":"Procore Technologies Canada","careers_url":"https://careers.procore.com/jobs?search=data+engineer&location=Canada","category":"Startups","scraper":"greenhouse","top100":False,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["Snowflake","Python","dbt","AWS"],"locations":["Remote Canada"],"salary_range":"$120K-$185K"},
    {"name":"SS&C Technologies Canada","careers_url":"https://www.ssctech.com/careers","category":"Startups","scraper":"custom","top100":False,"titles":["Senior Data Engineer","Data Architect","Analytics Engineer"],"stack":["Azure","Python","SQL","Spark"],"locations":["Toronto","Montreal"],"salary_range":"$100K-$175K"},
    {"name":"Tucows","careers_url":"https://www.tucows.com/careers","category":"Startups","scraper":"custom","top100":False,"titles":["Data/ML Infrastructure Engineer","Senior Data Engineer","Analytics Engineer"],"stack":["GCP","Python","Spark","SQL"],"locations":["Toronto","Remote"],"salary_range":"$105K-$175K"},
    {"name":"Plusgrade","careers_url":"https://www.plusgrade.com/careers","category":"Startups","scraper":"custom","top100":False,"titles":["Backend Engineer – Data","Data Engineer","Data Platform Engineer"],"stack":["Java","Scala","GCP","Python","SQL"],"locations":["Montreal"],"salary_range":"$105K-$175K"},
    {"name":"Paysafe Canada","careers_url":"https://www.paysafe.com/careers","category":"Startups","scraper":"custom","top100":False,"titles":["Data Engineer","Analytics Engineer"],"stack":["Azure","Python","SQL","Spark"],"locations":["Toronto","Montreal"],"salary_range":"$95K-$165K"},
    {"name":"NielsenIQ Canada","careers_url":"https://www.nielseniq.com/global/en/careers","category":"Startups","scraper":"custom","top100":False,"titles":["Senior Data Engineer","Analytics Engineer","Data Platform Engineer"],"stack":["GCP","AWS","Python","Spark","dbt"],"locations":["Toronto","Montreal"],"salary_range":"$100K-$175K"},

    # ══ BANKS & INSURANCE — ADDITIONAL ══
    {"name":"Barclays Canada","careers_url":"https://barclays.wd3.myworkdayjobs.com/External_Career_Site_Barclays?q=data+engineer&locationCountry=a30a87ed25634629aa6c3958aa2b91ea","category":"Banks","scraper":"workday","top100":False,"titles":["Senior Data Engineer","Data Platform Engineer","Analytics Engineer"],"stack":["Azure","Python","Spark","SQL","dbt"],"locations":["Toronto"],"salary_range":"$110K-$185K"},
    {"name":"iA Financial Group","careers_url":"https://ia.ca/careers","category":"Banks","scraper":"custom","top100":False,"titles":["Data Engineer","Senior Data Engineer","Analytics Engineer"],"stack":["Azure","Python","SQL","Power BI","dbt"],"locations":["Quebec City","Montreal","Toronto"],"salary_range":"$80K-$175K"},
    {"name":"Fairfax Financial","careers_url":"https://www.fairfax.ca/careers","category":"Banks","scraper":"custom","top100":False,"titles":["Data Engineer","Analytics Engineer","Data Architect"],"stack":["Azure","Python","SQL","Spark"],"locations":["Toronto"],"salary_range":"$95K-$170K"},
    {"name":"AIMCo","careers_url":"https://www.aimco.alberta.ca/about-aimco/careers","category":"Banks","scraper":"custom","top100":False,"titles":["Senior Data Engineer","Analytics Engineer","Data Architect"],"stack":["Azure","Python","SQL","dbt","Spark"],"locations":["Edmonton","Calgary"],"salary_range":"$100K-$180K"},
    {"name":"HOOPP","careers_url":"https://hoopp.wd10.myworkdayjobs.com/HOOPP?q=data+engineer&locationCountry=a30a87ed25634629aa6c3958aa2b91ea","category":"Banks","scraper":"workday","top100":False,"titles":["Senior Data Engineer","Analytics Engineer","Data Platform Engineer"],"stack":["Azure","Python","SQL","dbt","Power BI"],"locations":["Toronto"],"salary_range":"$100K-$175K"},

    # ══ FINTECH — ADDITIONAL ══
    {"name":"Robinhood Canada","careers_url":"https://careers.robinhood.com/careers?location=Canada","category":"Fintech","scraper":"greenhouse","top100":False,"titles":["Senior Data Engineer","Data Platform Engineer","Analytics Engineer"],"stack":["AWS","Python","Spark","Flink","SQL"],"locations":["Remote Canada"],"salary_range":"$140K-$220K"},
    {"name":"Affirm Canada","careers_url":"https://www.affirm.com/careers","category":"Fintech","scraper":"greenhouse","top100":False,"titles":["Senior Data Engineer","Analytics Engineer","Data Platform Engineer"],"stack":["AWS","Python","Spark","dbt","Airflow"],"locations":["Remote Canada"],"salary_range":"$135K-$215K"},
    {"name":"Klarna Canada","careers_url":"https://jobs.lever.co/klarna?search=data+engineer","category":"Fintech","scraper":"lever","top100":False,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["GCP","Python","dbt","Airflow","SQL"],"locations":["Remote Canada"],"salary_range":"$130K-$215K"},
    {"name":"Points.com","careers_url":"https://www.points.com/careers","category":"Fintech","scraper":"custom","top100":False,"titles":["Senior Data Engineer","Analytics Engineer","Data Platform Engineer"],"stack":["AWS","Python","dbt","Airflow","SQL"],"locations":["Toronto","Remote"],"salary_range":"$110K-$175K"},
    {"name":"FIS Canada","careers_url":"https://careers.fisglobal.com/jobs?keywords=data+engineer&location=Canada","category":"Fintech","scraper":"custom","top100":False,"titles":["Senior Data Engineer","Data Platform Engineer","Analytics Engineer"],"stack":["Azure","AWS","Python","Spark","SQL"],"locations":["Toronto","Montreal"],"salary_range":"$100K-$175K"},
    {"name":"Fiserv Canada","careers_url":"https://careers.fiserv.com/jobs?q=data+engineer&l=Canada","category":"Fintech","scraper":"custom","top100":False,"titles":["Senior Data Engineer","Data Platform Engineer","Analytics Engineer"],"stack":["Azure","AWS","Python","SQL","Spark"],"locations":["Toronto"],"salary_range":"$100K-$175K"},
    {"name":"Aimia","careers_url":"https://www.aimia.com/careers","category":"Fintech","scraper":"custom","top100":False,"titles":["Senior Data Engineer","Analytics Engineer","Data Scientist"],"stack":["AWS","Python","SQL","Spark","dbt"],"locations":["Montreal","Toronto"],"salary_range":"$100K-$165K"},
    {"name":"Clearco","careers_url":"https://www.clearco.com/careers","category":"Fintech","scraper":"custom","top100":False,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["GCP","Python","dbt","BigQuery","SQL"],"locations":["Toronto","Remote"],"salary_range":"$105K-$170K"},

    # ══ BIG TECH — ADDITIONAL ══
    {"name":"SAP Canada","careers_url":"https://jobs.sap.com/search/?q=data+engineer&location=Canada&locale=en_US","category":"Big Tech","scraper":"custom","top100":True,"titles":["Senior Data Engineer","Analytics Engineer","Cloud Data Engineer"],"stack":["Azure","AWS","Python","SQL","Spark"],"locations":["Toronto","Montreal","Vancouver","Ottawa"],"salary_range":"$110K-$195K"},
    {"name":"Ubisoft Canada","careers_url":"https://www.ubisoft.com/en-gb/company/careers/search?query=data+engineer&locations=Canada","category":"Big Tech","scraper":"custom","top100":False,"titles":["Senior Data Engineer","Analytics Engineer","Data Scientist"],"stack":["GCP","Python","BigQuery","SQL","dbt"],"locations":["Montreal","Toronto","Quebec City"],"salary_range":"$100K-$175K"},
    {"name":"Snap Canada","careers_url":"https://careers.snap.com/jobs?query=data+engineer&location=Canada","category":"Big Tech","scraper":"custom","top100":False,"titles":["Senior Data Engineer","Data Platform Engineer","Analytics Engineer"],"stack":["GCP","Python","Flink","Spark","SQL"],"locations":["Toronto","Vancouver"],"salary_range":"$140K-$225K"},
    {"name":"Zendesk Canada","careers_url":"https://zendesk.wd1.myworkdayjobs.com/zendesk?q=data+engineer&locationCountry=a30a87ed25634629aa6c3958aa2b91ea","category":"Big Tech","scraper":"workday","top100":False,"titles":["Senior Data Engineer","Analytics Engineer","Data Platform Engineer"],"stack":["AWS","Python","Snowflake","dbt","Airflow"],"locations":["Toronto","Remote"],"salary_range":"$130K-$215K"},
    {"name":"Okta Canada","careers_url":"https://www.okta.com/company/careers/engineering/","category":"Big Tech","scraper":"greenhouse","top100":False,"titles":["Senior Data Engineer","Data Platform Engineer","Analytics Engineer"],"stack":["AWS","Python","Snowflake","dbt","Spark"],"locations":["Toronto","Vancouver","Remote"],"salary_range":"$135K-$220K"},
    {"name":"Fortinet Canada","careers_url":"https://www.fortinet.com/corporate/about-us/careers","category":"Big Tech","scraper":"custom","top100":False,"titles":["Senior Data Engineer","Data Platform Engineer","Analytics Engineer"],"stack":["AWS","Python","Spark","SQL","Kafka"],"locations":["Burnaby BC","Toronto","Remote"],"salary_range":"$110K-$185K"},
    {"name":"Zynga Canada","careers_url":"https://jobs.smartrecruiters.com/Zynga/search?keyword=data+engineer+canada","category":"Big Tech","scraper":"smartrecruiters","top100":False,"titles":["Senior Data Engineer","Analytics Engineer","Data Scientist"],"stack":["GCP","BigQuery","Python","Spark","SQL"],"locations":["Toronto","Remote"],"salary_range":"$110K-$185K"},
    {"name":"Gartner Canada","careers_url":"https://jobs.gartner.com/jobs?q=data+engineer&l=Canada","category":"Big Tech","scraper":"custom","top100":False,"titles":["Senior Data Engineer","Analytics Engineer","Data Architect"],"stack":["Azure","AWS","Python","SQL","Spark"],"locations":["Toronto","Remote Canada"],"salary_range":"$115K-$190K"},
    {"name":"Verint Systems Canada","careers_url":"https://careers.verint.com","category":"Big Tech","scraper":"custom","top100":False,"titles":["Senior Data Engineer","Analytics Engineer","Data Platform Engineer"],"stack":["AWS","Python","Spark","SQL","Kafka"],"locations":["Remote Canada","Ottawa"],"salary_range":"$100K-$175K"},

    # ══ DATA TOOLS — ADDITIONAL ══
    {"name":"Prefect","careers_url":"https://boards.ashbyhq.com/prefect","category":"Data & Analytics","scraper":"ashby","top100":False,"titles":["Senior Data Engineer","Solutions Engineer"],"stack":["Python","Prefect","AWS","GCP","dbt"],"locations":["Remote Canada"],"salary_range":"$130K-$210K"},
    {"name":"Dagster","careers_url":"https://dagster.io/careers","category":"Data & Analytics","scraper":"greenhouse","top100":False,"titles":["Senior Data Engineer","Solutions Engineer"],"stack":["Python","Dagster","AWS","GCP","dbt"],"locations":["Remote Canada"],"salary_range":"$130K-$210K"},
    {"name":"HashiCorp Canada","careers_url":"https://www.hashicorp.com/jobs","category":"Data & Analytics","scraper":"custom","top100":False,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["AWS","GCP","Python","Terraform","SQL"],"locations":["Remote Canada"],"salary_range":"$130K-$210K"},

    # ══ CONSULTING — ADDITIONAL ══
    {"name":"Capco Canada","careers_url":"https://boards.greenhouse.io/capco","category":"Consulting","scraper":"greenhouse","top100":False,"titles":["Senior Data Engineer","Data Architect","Analytics Engineer"],"stack":["Azure","AWS","Python","Spark","SQL"],"locations":["Toronto","Montreal"],"salary_range":"$100K-$185K"},
    {"name":"HCL Technologies Canada","careers_url":"https://careers.hcltech.com/search-results?keywords=data+engineer&location=Canada&locale=en_US","category":"Consulting","scraper":"custom","top100":False,"titles":["Senior Data Engineer","Big Data Engineer","Analytics Engineer"],"stack":["Azure","AWS","Python","Spark","SQL"],"locations":["Toronto","Montreal","Vancouver"],"salary_range":"$85K-$165K"},
    {"name":"DXC Technology Canada","careers_url":"https://dxc.com/us/en/about-dxc/dxc-careers","category":"Consulting","scraper":"custom","top100":False,"titles":["Senior Data Engineer","Cloud Data Engineer","Analytics Engineer"],"stack":["Azure","AWS","Python","Spark","SQL"],"locations":["Toronto","Ottawa","Vancouver"],"salary_range":"$85K-$165K"},
    {"name":"Arcadis Canada","careers_url":"https://jobs.arcadis.com/search-jobs?keyword=data+engineer&location=Canada","category":"Consulting","scraper":"custom","top100":False,"titles":["Senior Data Engineer","Analytics Engineer","Data Architect"],"stack":["Azure","Python","SQL","Power BI","dbt"],"locations":["Vancouver","Toronto","Calgary"],"salary_range":"$90K-$170K"},

    # ══ HEALTHCARE — ADDITIONAL ══
    {"name":"Pfizer Canada","careers_url":"https://www.pfizer.ca/careers","category":"Healthcare","scraper":"custom","top100":False,"titles":["Senior Data Engineer","Analytics Engineer","Data Scientist"],"stack":["Azure","AWS","Python","Spark","SQL"],"locations":["Kirkland QC","Toronto"],"salary_range":"$100K-$180K"},
    {"name":"Johnson & Johnson Canada","careers_url":"https://jobs.jnj.com/search/?q=data+engineer&location=Canada","category":"Healthcare","scraper":"custom","top100":False,"titles":["Senior Data Engineer","Analytics Engineer","Data Scientist"],"stack":["AWS","Azure","Python","Spark","SQL"],"locations":["Toronto","Mississauga"],"salary_range":"$100K-$180K"},
    {"name":"Sanofi Canada","careers_url":"https://sanofi.wd3.myworkdayjobs.com/SanofiCareers/jobs?q=data+engineer","category":"Healthcare","scraper":"workday","top100":False,"titles":["Senior Data Engineer","Analytics Engineer","Data Scientist"],"stack":["Azure","AWS","Python","Spark","SQL"],"locations":["Toronto","Laval QC"],"salary_range":"$100K-$175K"},
    {"name":"Klick Health","careers_url":"https://www.klick.com/careers","category":"Healthcare","scraper":"custom","top100":False,"titles":["Senior Data Engineer","Analytics Engineer","Data Scientist"],"stack":["GCP","Python","dbt","BigQuery","SQL"],"locations":["Toronto"],"salary_range":"$100K-$175K"},
    {"name":"AbCellera Biologics","careers_url":"https://www.abcellera.com/careers","category":"Healthcare","scraper":"greenhouse","top100":False,"titles":["Senior Data Engineer","ML Data Engineer","Data Platform Engineer"],"stack":["AWS","Python","Spark","SQL","dbt"],"locations":["Vancouver"],"salary_range":"$110K-$185K"},

    # ══ RETAIL — ADDITIONAL ══
    {"name":"Metro Inc","careers_url":"https://www.metro.ca/en/corporate/careers","category":"Retail","scraper":"custom","top100":False,"titles":["Senior Data Engineer","Analytics Engineer","BI Developer"],"stack":["Azure","Python","SQL","Power BI","dbt"],"locations":["Montreal","Toronto"],"salary_range":"$90K-$170K"},
    {"name":"Instacart Canada","careers_url":"https://instacart.careers/jobs?query=data+engineer","category":"Retail","scraper":"greenhouse","top100":False,"titles":["Senior Data Engineer","Analytics Engineer","Data Platform Engineer"],"stack":["GCP","BigQuery","Python","dbt","Airflow"],"locations":["Toronto","Remote Canada"],"salary_range":"$140K-$220K"},
    {"name":"Etsy Canada","careers_url":"https://jobs.smartrecruiters.com/Etsy/search?keyword=data+engineer+canada","category":"Retail","scraper":"smartrecruiters","top100":False,"titles":["Senior Data Engineer","Analytics Engineer","Data Platform Engineer"],"stack":["GCP","BigQuery","Python","dbt","Airflow"],"locations":["Remote Canada"],"salary_range":"$140K-$225K"},

    # ══ GOVERNMENT — ADDITIONAL ══
    {"name":"CMHC","careers_url":"https://www.cmhc-schl.gc.ca/careers","category":"Government","scraper":"custom","top100":False,"titles":["Senior Data Engineer","Analytics Engineer","Data Architect"],"stack":["Azure","Python","SQL","Power BI","dbt"],"locations":["Ottawa","Toronto"],"salary_range":"$85K-$165K"},
    {"name":"Public Health Agency of Canada","careers_url":"https://www.canada.ca/en/public-health/corporate/jobs.html","category":"Government","scraper":"custom","top100":False,"titles":["Data Engineer","Senior Data Engineer","Analytics Engineer"],"stack":["Azure","Python","SQL","R","Power BI"],"locations":["Ottawa","Montreal","Toronto"],"salary_range":"$80K-$155K"},

    # ══ STARTUPS — ADDITIONAL ══
    {"name":"Prodigy Education","careers_url":"https://www.prodigygame.com/main-en/careers","category":"Startups","scraper":"custom","top100":False,"titles":["Senior Data Engineer","Analytics Engineer","Data Platform Engineer"],"stack":["GCP","Python","BigQuery","dbt","SQL"],"locations":["Toronto"],"salary_range":"$100K-$160K"},
    {"name":"Vendasta","careers_url":"https://www.vendasta.com/careers","category":"Startups","scraper":"custom","top100":False,"titles":["Senior Data Engineer","Analytics Engineer","Data Platform Engineer"],"stack":["GCP","Python","BigQuery","dbt","Airflow"],"locations":["Saskatoon","Remote"],"salary_range":"$100K-$165K"},
    {"name":"Tulip Retail","careers_url":"https://tulip.com/careers","category":"Startups","scraper":"greenhouse","top100":False,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["AWS","Python","SQL","dbt"],"locations":["Toronto"],"salary_range":"$100K-$165K"},
    {"name":"MindBridge AI","careers_url":"https://www.mindbridge.ai/careers","category":"Startups","scraper":"custom","top100":False,"titles":["Senior Data Engineer","ML Data Engineer","Analytics Engineer"],"stack":["AWS","Python","Spark","SQL","dbt"],"locations":["Ottawa","Remote"],"salary_range":"$100K-$165K"},
    {"name":"KUBRA","careers_url":"https://kubra.com/careers","category":"Startups","scraper":"custom","top100":False,"titles":["Senior Data Engineer","Analytics Engineer","Data Platform Engineer"],"stack":["Azure","Python","SQL","dbt","Power BI"],"locations":["Mississauga","Toronto"],"salary_range":"$95K-$160K"},
    {"name":"Resolver","careers_url":"https://www.resolver.com/company/careers","category":"Startups","scraper":"custom","top100":False,"titles":["Senior Data Engineer","Analytics Engineer","Data Platform Engineer"],"stack":["Azure","Python","SQL","dbt","Power BI"],"locations":["Toronto"],"salary_range":"$100K-$165K"},
    {"name":"SOTI Inc","careers_url":"https://www.soti.net/careers","category":"Startups","scraper":"custom","top100":False,"titles":["Senior Data Engineer","Analytics Engineer","Data Platform Engineer"],"stack":["Azure","Python","SQL","Spark"],"locations":["Mississauga","Toronto"],"salary_range":"$95K-$160K"},
    {"name":"Wattpad / Naver Canada","careers_url":"https://www.wattpad.com/careers","category":"Startups","scraper":"lever","top100":False,"titles":["Senior Data Engineer","Analytics Engineer","Data Platform Engineer"],"stack":["GCP","Python","BigQuery","Airflow","SQL"],"locations":["Toronto"],"salary_range":"$105K-$170K"},
]
