import os
from dotenv import load_dotenv

load_dotenv()

EMAIL_CONFIG = {
    "sender_email":    os.getenv("GMAIL_SENDER", "your_gmail@gmail.com"),
    "sender_password": os.getenv("GMAIL_APP_PASSWORD", "your_app_password"),
    "recipient_email": os.getenv("GMAIL_RECIPIENT", "your_gmail@gmail.com"),
    "smtp_host":       "smtp.gmail.com",
    "smtp_port":       587,
}

SEARCH_KEYWORDS = [
    "Senior Data Engineer", "Data Engineer", "Analytics Engineer",
    "Data Platform Engineer", "ML Data Engineer", "Cloud Data Engineer",
]

EXPERIENCE_LEVELS = ["Senior", "Mid-Level", "Entry Level", "Staff", "Principal"]

TARGET_LOCATIONS = [
    "Canada", "Toronto", "Vancouver", "Calgary",
    "Edmonton", "Halifax", "Ottawa", "Montreal", "Remote",
]

MAX_JOBS_PER_EMAIL = 30
SEEN_JOBS_FILE = "data/seen_jobs.json"

COMPANIES = [
    {"name":"RBC","careers_url":"https://jobs.rbc.com/ca/en/search-results?keywords=data+engineer","category":"Banks","scraper":"workday","top100":True,"titles":["Senior Data Engineer","Analytics Engineer","Data Platform Engineer"],"stack":["Azure","Databricks","Spark","Python","dbt"],"locations":["Toronto","Vancouver","Calgary"],"salary_range":"$85K-$215K"},
    {"name":"TD Bank","careers_url":"https://jobs.td.com/en-CA/jobs/?keyword=data+engineer","category":"Banks","scraper":"custom","top100":True,"titles":["Senior Data Engineer","ETL Developer","Analytics Engineer"],"stack":["Azure","Snowflake","Python","dbt","Airflow"],"locations":["Toronto","Montreal"],"salary_range":"$80K-$210K"},
    {"name":"Scotiabank","careers_url":"https://jobs.scotiabank.com/search/?q=data+engineer&l=Canada","category":"Banks","scraper":"custom","top100":True,"titles":["Senior Data Engineer","Data Platform Engineer","Analytics Engineer"],"stack":["Azure","Databricks","PySpark","Python","dbt"],"locations":["Toronto","Montreal"],"salary_range":"$80K-$212K"},
    {"name":"CIBC","careers_url":"https://cibc.wd3.myworkdayjobs.com/search?q=data+engineer","category":"Banks","scraper":"workday","top100":True,"titles":["Senior Data Engineer","ETL Developer","Analytics Engineer"],"stack":["Azure","Spark","Python","SQL","ADF"],"locations":["Toronto"],"salary_range":"$78K-$208K"},
    {"name":"BMO Financial Group","careers_url":"https://bmo.wd3.myworkdayjobs.com/External/jobs?q=data+engineer","category":"Banks","scraper":"workday","top100":True,"titles":["Senior Data Engineer","Data Platform Engineer","Analytics Engineer"],"stack":["Azure","Databricks","Python","dbt","Spark"],"locations":["Toronto","Montreal"],"salary_range":"$82K-$215K"},
    {"name":"National Bank of Canada","careers_url":"https://nbc.wd3.myworkdayjobs.com/search?q=data+engineer","category":"Banks","scraper":"workday","top100":True,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["Azure","Python","Spark","SQL","dbt"],"locations":["Montreal","Toronto"],"salary_range":"$78K-$210K"},
    {"name":"Manulife","careers_url":"https://manulife.wd3.myworkdayjobs.com/MANULIFE_CAREERS/jobs?q=data+engineer","category":"Banks","scraper":"workday","top100":True,"titles":["Senior Data Engineer","Data Platform Engineer","Analytics Engineer"],"stack":["AWS","Snowflake","Python","dbt","Airflow"],"locations":["Toronto","Waterloo"],"salary_range":"$82K-$215K"},
    {"name":"Goldman Sachs Canada","careers_url":"https://goldmansachs.com/careers","category":"Banks","scraper":"custom","top100":True,"titles":["Senior Data Engineer","Data Infrastructure Engineer"],"stack":["Python","Spark","Kafka","SQL","GCP"],"locations":["Toronto"],"salary_range":"$140K-$220K"},
    {"name":"JP Morgan Canada","careers_url":"https://jpmorgan.com/careers","category":"Banks","scraper":"custom","top100":True,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["Python","Spark","AWS","SQL","Airflow"],"locations":["Toronto"],"salary_range":"$135K-$215K"},
    {"name":"Bloomberg Canada","careers_url":"https://bloomberg.com/careers","category":"Fintech","scraper":"custom","top100":True,"titles":["Senior Software Engineer Data","Data Engineer","Feeds Engineer"],"stack":["Python","C++","Kafka","Spark","AWS"],"locations":["Toronto"],"salary_range":"$155K-$260K"},
    {"name":"Wealthsimple","careers_url":"https://jobs.lever.co/wealthsimple?search=data+engineer","category":"Fintech","scraper":"lever","top100":True,"titles":["Senior Data Engineer","Data Platform Engineer","Analytics Engineer"],"stack":["GCP","BigQuery","dbt","Airflow","Python"],"locations":["Toronto","Remote"],"salary_range":"$128K-$212K"},
    {"name":"Capital One Canada","careers_url":"https://www.capitalonecareers.com/search-jobs?k=data+engineer&l=Canada","category":"Fintech","scraper":"custom","top100":True,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["AWS","Spark","Python","Snowflake","dbt"],"locations":["Toronto"],"salary_range":"$128K-$218K"},
    {"name":"Stripe Canada","careers_url":"https://stripe.com/jobs/search?query=data+engineer","category":"Fintech","scraper":"custom","top100":True,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["GCP","BigQuery","dbt","Python","Spark"],"locations":["Remote Canada"],"salary_range":"$155K-$275K"},
    {"name":"Visa Canada","careers_url":"https://careers.visa.com","category":"Fintech","scraper":"custom","top100":True,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["Azure","GCP","Spark","Python","SQL"],"locations":["Toronto","Vancouver"],"salary_range":"$130K-$210K"},
    {"name":"Mastercard Canada","careers_url":"https://mastercard.wd1.myworkdayjobs.com/search?q=data+engineer","category":"Fintech","scraper":"workday","top100":True,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["GCP","BigQuery","Python","dbt","Spark"],"locations":["Toronto"],"salary_range":"$125K-$200K"},
    {"name":"Google Canada","careers_url":"https://careers.google.com/jobs/results/?q=data+engineer&location=Canada","category":"Big Tech","scraper":"custom","top100":True,"titles":["Software Engineer Data Infrastructure","Technical Solutions Engineer","Analytics Engineer"],"stack":["GCP","BigQuery","Dataflow","Python","Go"],"locations":["Toronto","Waterloo","Montreal"],"salary_range":"$145K-$340K+"},
    {"name":"Microsoft Canada","careers_url":"https://jobs.careers.microsoft.com/global/en/search?q=data+engineer&lc=Canada","category":"Big Tech","scraper":"custom","top100":True,"titles":["Senior Data Engineer","Data Platform Engineer","Principal Data Engineer"],"stack":["Azure","Databricks","Fabric","Python","Spark"],"locations":["Toronto","Vancouver","Ottawa"],"salary_range":"$130K-$285K"},
    {"name":"Amazon / AWS Canada","careers_url":"https://www.amazon.jobs/en/search?base_query=data+engineer&loc_query=Canada","category":"Big Tech","scraper":"custom","top100":True,"titles":["Senior Data Engineer","Business Intelligence Engineer","Data Engineer II"],"stack":["AWS","Redshift","Glue","Python","Spark"],"locations":["Toronto","Vancouver"],"salary_range":"$118K-$248K"},
    {"name":"Meta Canada","careers_url":"https://www.metacareers.com/jobs?q=data+engineer","category":"Big Tech","scraper":"custom","top100":True,"titles":["Senior Data Engineer","Analytics Engineer","Data Infrastructure Engineer"],"stack":["Spark","Presto","Hive","Python","Airflow"],"locations":["Toronto"],"salary_range":"$140K-$270K"},
    {"name":"Apple Canada","careers_url":"https://jobs.apple.com/en-ca/search?search=data+engineer&sort=newest","category":"Big Tech","scraper":"custom","top100":True,"titles":["Senior Data Engineer","ML Data Engineer","Data Infrastructure Engineer"],"stack":["Python","Spark","AWS","Kafka","SQL"],"locations":["Toronto","Vancouver"],"salary_range":"$165K-$275K"},
    {"name":"Netflix Canada","careers_url":"https://jobs.netflix.com/search?q=data+engineer","category":"Big Tech","scraper":"custom","top100":True,"titles":["Senior Data Engineer","Senior SWE Data Platform","Analytics Engineer"],"stack":["Spark","Flink","Iceberg","Python","Maestro"],"locations":["Remote Canada"],"salary_range":"$195K-$295K"},
    {"name":"Shopify","careers_url":"https://www.shopify.com/careers/search?keywords=data+engineer","category":"Big Tech","scraper":"greenhouse","top100":True,"titles":["Senior Data Engineer","Staff Data Engineer","Analytics Engineer"],"stack":["GCP","Trino","Spark","dbt","Python"],"locations":["Ottawa","Toronto","Remote"],"salary_range":"$120K-$262K"},
    {"name":"Uber Canada","careers_url":"https://www.uber.com/global/en/careers/list/?query=data+engineer&location=Canada","category":"Big Tech","scraper":"custom","top100":True,"titles":["Senior SWE Data","Data Platform Engineer","Analytics Engineer"],"stack":["Flink","Kafka","Hudi","Python","Spark"],"locations":["Toronto"],"salary_range":"$165K-$275K"},
    {"name":"LinkedIn Canada","careers_url":"https://careers.linkedin.com/jobs?keywords=data+engineer&location=Canada","category":"Big Tech","scraper":"custom","top100":True,"titles":["Senior Data Engineer","Analytics Engineer","Staff Data Engineer"],"stack":["Kafka","Samza","Spark","Python","Espresso"],"locations":["Toronto"],"salary_range":"$162K-$265K"},
    {"name":"Databricks Canada","careers_url":"https://www.databricks.com/company/careers/open-positions?search=data+engineer","category":"Big Tech","scraper":"greenhouse","top100":True,"titles":["Solutions Architect Data","Senior Data Engineer","Field Engineer"],"stack":["Databricks","Delta Lake","Spark","Unity Catalog","MLflow"],"locations":["Remote Canada"],"salary_range":"$152K-$260K"},
    {"name":"Snowflake Canada","careers_url":"https://careers.snowflake.com/jobs?search=data+engineer&location=Canada","category":"Big Tech","scraper":"lever","top100":True,"titles":["Solutions Engineer","Data Cloud Architect","Senior Data Engineer"],"stack":["Snowflake","Python","dbt","SQL","Airflow"],"locations":["Remote Canada"],"salary_range":"$155K-$248K"},
    {"name":"Confluent Canada","careers_url":"https://careers.confluent.io/jobs?search=data+engineer","category":"Big Tech","scraper":"greenhouse","top100":True,"titles":["Solutions Engineer","Data Streaming Engineer"],"stack":["Kafka","Flink","Python","Java","ksqlDB"],"locations":["Remote Canada"],"salary_range":"$155K-$245K"},
    {"name":"OpenAI Canada","careers_url":"https://openai.com/careers","category":"Big Tech","scraper":"greenhouse","top100":True,"titles":["Data Engineer","ML Data Engineer","Data Platform Engineer"],"stack":["AWS","Python","Spark","SQL","dbt"],"locations":["Toronto"],"salary_range":"$185K-$290K"},
    {"name":"Cohere AI","careers_url":"https://cohere.com/careers","category":"Big Tech","scraper":"greenhouse","top100":True,"titles":["Senior Data Engineer","ML Data Engineer"],"stack":["GCP","Python","Spark","SQL","dbt"],"locations":["Toronto"],"salary_range":"$175K-$278K"},
    {"name":"Nvidia Canada","careers_url":"https://nvidia.wd5.myworkdayjobs.com/search?q=data+engineer&locations=Canada","category":"Big Tech","scraper":"workday","top100":True,"titles":["Senior Data Engineer","ML Data Engineer","Principal Data Engineer"],"stack":["GCP","AWS","Python","Spark","CUDA"],"locations":["Toronto","Waterloo","Vancouver"],"salary_range":"$172K-$272K"},
    {"name":"Salesforce Canada","careers_url":"https://salesforce.wd12.myworkdayjobs.com/search?q=data+engineer","category":"Big Tech","scraper":"workday","top100":True,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["GCP","Spark","Python","dbt","Tableau"],"locations":["Toronto","Vancouver"],"salary_range":"$130K-$225K"},
    {"name":"Accenture Canada","careers_url":"https://www.accenture.com/ca-en/careers/jobsearch?jk=data+engineer","category":"Consulting","scraper":"custom","top100":True,"titles":["Data Engineer Analyst","Senior Data Engineer Manager","Cloud Data Engineer","Analytics Engineer"],"stack":["Azure","AWS","GCP","Spark","Python"],"locations":["Toronto","Montreal","Vancouver","Ottawa"],"salary_range":"$75K-$225K"},
    {"name":"Deloitte Canada","careers_url":"https://careers.deloitte.ca/search-jobs/?k=data+engineer&l=Canada","category":"Consulting","scraper":"custom","top100":True,"titles":["Data Engineer Analyst","Senior Data Engineer","Cloud Data Engineer","Analytics Engineer"],"stack":["Azure","Databricks","Python","Spark","dbt"],"locations":["Toronto","Montreal","Calgary","Vancouver"],"salary_range":"$75K-$290K"},
    {"name":"PwC Canada","careers_url":"https://www.pwc.com/ca/en/careers/job-search.html?q=data+engineer","category":"Consulting","scraper":"custom","top100":True,"titles":["Data Engineer Associate","Senior Data Engineer","Analytics Engineer"],"stack":["Azure","AWS","Python","dbt","Spark"],"locations":["Toronto","Vancouver","Calgary"],"salary_range":"$75K-$215K"},
    {"name":"EY Canada","careers_url":"https://careers.ey.com/ey/search/?q=data+engineer&locationsearch=Canada","category":"Consulting","scraper":"custom","top100":True,"titles":["Senior Data Engineer","Analytics Engineer","Cloud Data Engineer"],"stack":["Azure","AWS","GCP","Python","Spark"],"locations":["Toronto","Montreal","Vancouver"],"salary_range":"$74K-$208K"},
    {"name":"McKinsey Canada","careers_url":"https://www.mckinsey.com/careers/search-jobs?query=data+engineer","category":"Consulting","scraper":"custom","top100":True,"titles":["Senior Data Engineer","QuantumBlack Data Engineer"],"stack":["GCP","Python","Spark","dbt","SQL"],"locations":["Toronto","Montreal"],"salary_range":"$110K-$238K"},
    {"name":"IBM Canada","careers_url":"https://www.ibm.com/ca-en/employment/jobs/?q=data+engineer&country=Canada","category":"Consulting","scraper":"custom","top100":True,"titles":["Senior Data Engineer","Analytics Engineer","DataOps Engineer"],"stack":["IBM Cloud","AWS","Python","Spark","SQL"],"locations":["Toronto","Ottawa","Montreal"],"salary_range":"$80K-$215K"},
    {"name":"CGI Group","careers_url":"https://www.cgi.com/canada/en-ca/careers?search=data+engineer","category":"Consulting","scraper":"custom","top100":True,"titles":["Senior Data Engineer","ETL Developer","Analytics Engineer","BI Developer"],"stack":["Azure","AWS","Python","Spark","SQL"],"locations":["Toronto","Ottawa","Montreal","Vancouver"],"salary_range":"$78K-$202K"},
    {"name":"TCS Canada","careers_url":"https://www.tcs.com/careers","category":"Consulting","scraper":"custom","top100":False,"titles":["Senior Data Engineer","Cloud Data Engineer"],"stack":["Azure","AWS","Python","Spark","SQL"],"locations":["Toronto","Vancouver","Calgary"],"salary_range":"$85K-$175K"},
    {"name":"Wipro Canada","careers_url":"https://careers.wipro.com/careers-home/jobs?keyword=data+engineer&location=Canada","category":"Consulting","scraper":"custom","top100":False,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["Azure","AWS","Python","Spark","SQL"],"locations":["Toronto","Vancouver"],"salary_range":"$85K-$168K"},
    {"name":"dbt Labs Canada","careers_url":"https://www.getdbt.com/about-us/careers?search=data+engineer","category":"Data & Analytics","scraper":"greenhouse","top100":True,"titles":["Senior Data Engineer","Analytics Engineer","Solutions Architect"],"stack":["dbt","Snowflake","BigQuery","Python","SQL"],"locations":["Remote Canada"],"salary_range":"$145K-$215K"},
    {"name":"Fivetran Canada","careers_url":"https://www.fivetran.com/careers?search=data+engineer","category":"Data & Analytics","scraper":"greenhouse","top100":True,"titles":["Senior Data Engineer","Solutions Engineer"],"stack":["Fivetran","Python","SQL","dbt","Snowflake"],"locations":["Remote Canada"],"salary_range":"$155K-$205K"},
    {"name":"Palantir Canada","careers_url":"https://www.palantir.com/careers/search?q=data+engineer&location=Canada","category":"Data & Analytics","scraper":"greenhouse","top100":True,"titles":["Forward Deployed Engineer","Data Engineer"],"stack":["Foundry","Python","Spark","Java","Ontology"],"locations":["Toronto"],"salary_range":"$155K-$260K"},
    {"name":"Datadog Canada","careers_url":"https://www.datadoghq.com/careers/","category":"Data & Analytics","scraper":"greenhouse","top100":True,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["AWS","Python","Spark","Go","SQL"],"locations":["Toronto","Remote"],"salary_range":"$140K-$220K"},
    {"name":"Rogers Communications","careers_url":"https://jobs.rogers.com/search/?q=data+engineer&l=Canada","category":"Telecom","scraper":"custom","top100":True,"titles":["Senior Data Engineer","Data Platform Engineer","Analytics Engineer","BI Developer"],"stack":["Azure","Databricks","Python","SQL","Power BI"],"locations":["Toronto","Calgary"],"salary_range":"$82K-$212K"},
    {"name":"Bell Canada","careers_url":"https://jobs.bell.ca/ca/en/search-results?keywords=data+engineer","category":"Telecom","scraper":"workday","top100":True,"titles":["Senior Data Engineer","ETL Developer","Analytics Engineer"],"stack":["Azure","Python","Spark","SQL","ADF"],"locations":["Toronto","Montreal"],"salary_range":"$80K-$210K"},
    {"name":"Telus","careers_url":"https://www.telus.com/en/about/careers/search?q=data+engineer","category":"Telecom","scraper":"custom","top100":True,"titles":["Senior Data Engineer","Cloud Data Engineer","Analytics Engineer","ML Data Engineer"],"stack":["GCP","BigQuery","Python","dbt","Airflow"],"locations":["Vancouver","Calgary","Toronto"],"salary_range":"$82K-$215K"},
    {"name":"Loblaw Companies","careers_url":"https://myview.wd3.myworkdayjobs.com/loblaw/jobs?q=data+engineer","category":"Retail","scraper":"workday","top100":True,"titles":["Senior Data Engineer","Data Platform Engineer","Analytics Engineer"],"stack":["GCP","BigQuery","Python","dbt","Airflow"],"locations":["Toronto","Brampton"],"salary_range":"$82K-$212K"},
    {"name":"Walmart Canada","careers_url":"https://walmart.wd5.myworkdayjobs.com/WalmartExternal/jobs?q=data+engineer","category":"Retail","scraper":"workday","top100":True,"titles":["Senior Data Engineer","Data Platform Engineer","Analytics Engineer"],"stack":["Azure","GCP","Spark","Python","SQL"],"locations":["Mississauga","Toronto"],"salary_range":"$118K-$210K"},
    {"name":"Canadian Tire Corporation","careers_url":"https://careers.canadiantire.ca/search/?q=data+engineer","category":"Retail","scraper":"custom","top100":True,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["Azure","Databricks","Python","SQL","dbt"],"locations":["Toronto"],"salary_range":"$115K-$208K"},
    {"name":"Lululemon Canada","careers_url":"https://careers.lululemon.com/en-us/jobs","category":"Retail","scraper":"custom","top100":True,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["GCP","BigQuery","Python","dbt","Airflow"],"locations":["Vancouver"],"salary_range":"$120K-$195K"},
    {"name":"Air Canada","careers_url":"https://aircanada.wd1.myworkdayjobs.com/search?q=data+engineer","category":"Retail","scraper":"workday","top100":True,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["Azure","GCP","Python","SQL","dbt"],"locations":["Montreal","Toronto"],"salary_range":"$110K-$190K"},
    {"name":"Ontario Health","careers_url":"https://jobs.ontariohealth.ca/search/?q=data+engineer","category":"Healthcare","scraper":"custom","top100":True,"titles":["Senior Data Engineer","Health Data Engineer","Analytics Engineer","BI Developer"],"stack":["Azure","Python","SQL","Power BI","ADF"],"locations":["Toronto","Ottawa"],"salary_range":"$80K-$200K"},
    {"name":"PointClickCare","careers_url":"https://www.pointclickcare.com/careers/","category":"Healthcare","scraper":"greenhouse","top100":True,"titles":["Senior Data Engineer","Analytics Engineer","Principal Data Engineer"],"stack":["Azure","Databricks","Python","SQL","dbt"],"locations":["Mississauga","Toronto"],"salary_range":"$112K-$188K"},
    {"name":"TELUS Health","careers_url":"https://www.telus.com/en/health/careers","category":"Healthcare","scraper":"custom","top100":True,"titles":["Senior Data Engineer","Healthcare Data Engineer"],"stack":["GCP","Python","dbt","BigQuery","Airflow"],"locations":["Vancouver","Toronto","Remote"],"salary_range":"$110K-$195K"},
    {"name":"Enbridge","careers_url":"https://enbridge.com/careers/search?keywords=data+engineer","category":"Energy","scraper":"custom","top100":True,"titles":["Senior Data Engineer","Data Platform Engineer","Analytics Engineer"],"stack":["Azure","Databricks","Python","SQL","ADF"],"locations":["Calgary","Toronto"],"salary_range":"$82K-$208K"},
    {"name":"Suncor Energy","careers_url":"https://suncor.com/en/careers/search?q=data+engineer","category":"Energy","scraper":"custom","top100":True,"titles":["Senior Data Engineer","Analytics Engineer","DataOps Engineer"],"stack":["Azure","Databricks","Python","SQL","Spark"],"locations":["Calgary"],"salary_range":"$115K-$208K"},
    {"name":"TC Energy","careers_url":"https://careers.tcenergy.com/search-jobs/?keyword=data+engineer","category":"Energy","scraper":"custom","top100":False,"titles":["Data Engineer","Senior Data Engineer"],"stack":["Azure","Python","SQL","Power BI"],"locations":["Calgary","Toronto"],"salary_range":"$90K-$175K"},
    {"name":"Government of Canada","careers_url":"https://jobs-emplois.gc.ca/job-emploi/results-resultats?k=data+engineer&l=Canada","category":"Government","scraper":"custom","top100":True,"titles":["Data Engineer IT-02","Senior Data Engineer IT-04","Cloud Data Engineer"],"stack":["Azure","AWS","Python","SQL","Power BI"],"locations":["Ottawa","Toronto","Montreal"],"salary_range":"$75K-$175K"},
    {"name":"Statistics Canada","careers_url":"https://statcan.gc.ca/careers","category":"Government","scraper":"custom","top100":True,"titles":["Data Engineer EC-04","Senior Data Engineer EC-06","Analytics Engineer"],"stack":["Azure","Python","R","SQL","Spark"],"locations":["Ottawa","Toronto"],"salary_range":"$78K-$170K"},
    {"name":"Bank of Canada","careers_url":"https://careers.bankofcanada.ca/search/?q=data+engineer","category":"Government","scraper":"custom","top100":True,"titles":["Senior Data Engineer","Cloud Data Engineer","Analytics Engineer"],"stack":["Azure","AWS","Python","Spark","SQL"],"locations":["Ottawa","Toronto"],"salary_range":"$110K-$198K"},
    {"name":"Export Development Canada","careers_url":"https://edc.ca/careers","category":"Government","scraper":"custom","top100":True,"titles":["Senior Data Engineer","Analytics Engineer"],"stack":["AWS","Python","Spark","dbt","SQL"],"locations":["Ottawa","Toronto"],"salary_range":"$110K-$195K"},
    {"name":"Coveo","careers_url":"https://www.coveo.com/en/company/careers?search=data+engineer","category":"Startups","scraper":"greenhouse","top100":True,"titles":["Senior Data Engineer","Analytics Engineer","ML Data Engineer"],"stack":["GCP","BigQuery","Python","dbt","Spark"],"locations":["Quebec City","Toronto","Remote"],"salary_range":"$118K-$168K"},
    {"name":"Lightspeed Commerce","careers_url":"https://www.lightspeedhq.com/careers/?search=data+engineer","category":"Startups","scraper":"greenhouse","top100":True,"titles":["Senior Data Engineer","Analytics Engineer","Data Platform Engineer"],"stack":["GCP","BigQuery","Python","dbt","Airflow"],"locations":["Montreal","Toronto"],"salary_range":"$120K-$165K"},
    {"name":"Thomson Reuters","careers_url":"https://thomsonreuters.wd5.myworkdayjobs.com/External_Career_Site/jobs?q=data+engineer","category":"Startups","scraper":"workday","top100":True,"titles":["Senior Data Engineer","Analytics Engineer","Principal Data Engineer"],"stack":["GCP","AWS","Python","Spark","dbt"],"locations":["Toronto"],"salary_range":"$125K-$205K"},
    {"name":"Clio","careers_url":"https://www.clio.com/careers/?search=data+engineer","category":"Startups","scraper":"greenhouse","top100":True,"titles":["Senior Data Engineer","Analytics Engineer","Staff Data Engineer"],"stack":["GCP","BigQuery","Python","dbt","Airflow"],"locations":["Burnaby BC","Toronto","Remote"],"salary_range":"$120K-$200K"},
    {"name":"Kinaxis","careers_url":"https://www.kinaxis.com/en/careers?search=data+engineer","category":"Startups","scraper":"greenhouse","top100":True,"titles":["Senior Data Engineer","Analytics Engineer","Data Platform Engineer"],"stack":["AWS","Python","SQL","dbt","Airflow"],"locations":["Ottawa","Remote"],"salary_range":"$118K-$158K"},
    {"name":"Borealis AI (RBC)","careers_url":"https://www.borealisai.com/careers/","category":"Startups","scraper":"greenhouse","top100":True,"titles":["Senior ML Data Engineer","Data Platform Engineer","Research Data Engineer"],"stack":["GCP","Python","Spark","SQL","PyTorch"],"locations":["Toronto","Vancouver","Edmonton"],"salary_range":"$140K-$192K"},
    {"name":"Geotab","careers_url":"https://www.geotab.com/careers/","category":"Startups","scraper":"greenhouse","top100":True,"titles":["Senior Data Engineer","Data Platform Engineer","Analytics Engineer"],"stack":["GCP","BigQuery","Python","dbt","Airflow"],"locations":["Oakville ON","Remote"],"salary_range":"$120K-$180K"},
    {"name":"Layer6 AI (TD)","careers_url":"https://layer6.ai/careers/","category":"Startups","scraper":"custom","top100":True,"titles":["Senior ML Data Engineer","Data Platform Engineer"],"stack":["GCP","AWS","Python","Spark","SQL"],"locations":["Toronto"],"salary_range":"$142K-$195K"},
]
